Repository microsoft/lisa, pull requests merged in 2019-06, with the labels that each got.

#290 dpdk: retry to download source on transient connectivity errors
  Testscripts/Linux/dpdkSetup.sh
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Linux/utils.sh
Labels: PR-Verified, dpdk

#285 Hyper-V: Fix the static disk device name test issue
  Testscripts/Linux/STOR_VHDXResize_GrowFSAfterResize.sh
  Testscripts/Linux/STOR_VHDXResize_PartitionDisk.sh
  Testscripts/Windows/STOR-VHDX-RESIZE-GROWFS.ps1
Labels: 🐞 Bug

#298 GPU-NVIDIA driver install: Improve log collection
  LISAv2-Framework.psm1
  Libraries/Azure.psm1
  Testscripts/Linux/gpu-driver-install.sh
  Testscripts/Windows/GPU-DRIVER-INSTALL.ps1
Labels: PR-Verified, 🐞 Bug

#288 Fix: handled devided by zero exception in Get-SubscriptionUsage.ps1
  Utilities/Get-SubscriptionUsage.ps1
Labels: Approved, PR-Verified

#307 Fix infinite loop found when delete locked RG.
  Libraries/Azure.psm1
Labels: 🐞 Bug

#236 Azure: Restart VM from shell if Azure fails to restart the VM
  Libraries/CommonFunctions.psm1
  TestProviders/AzureProvider.psm1
Labels: PR-Verified

#304 Update ntttcp version into latest release one 1.4.0
  Testscripts/Linux/perf_ntttcp.sh
  Testscripts/Linux/utils.sh
  XML/Other/ReplaceableTestParameters.xml
Labels: PR-Verified, 🐞 Bug

#314 RELOAD-MODULES-SMP - Add default route when miss it after run ip link down/up
  Testscripts/Linux/RELOAD-MODULES.sh
Labels: 🐞 Bug

#312 Get-IPv4ViaKVP: Fix infinite loop
  Libraries/IntegrationServiceLibrary.psm1
Labels: 🐞 Bug

#302 Fix test time out issue for dynamic memory test cases
  Libraries/IntegrationServiceLibrary.psm1
  Testscripts/Windows/DM-HOTADD-EATMEMORY.ps1
  Testscripts/Windows/DM-HOTADD-STRESS-APP.ps1
  Testscripts/Windows/DM-MAXMEMHONOR.ps1
  Testscripts/Windows/DM-MINMEMHONOR.ps1
  Testscripts/Windows/DM-PRESSURE-CHANGES-DEMAND.ps1
  Testscripts/Windows/DM-REMOVE-THEN-PRESSURE.ps1
  Testscripts/Windows/DM_HIGH-PRIORITY.ps1
  Testscripts/Windows/DM_REMOVE-UNDER-PRESSURE.ps1
  XML/TestCases/FunctionalTests-DynamicMemory.xml
Labels: PR-Verified, 🐞 Bug

#321 VERIFY-DPDK-FAILSAFE-DURING-TRAFFIC - Refine log info.
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
Labels: enhancement

#320 Function Publish-App: Install build dependencies
  Libraries/CommonFunctions.psm1
Labels: enhancement, 🐞 Bug

#325 Reload Modules TC: Various improvements
  Testscripts/Linux/RELOAD-MODULES.sh
  Testscripts/Windows/RELOAD-MODULES.ps1
Labels: enhancement

#206 LISAv2: Migration from AzureRm modules to Az modules
  JenkinsPipelines/Scripts/UpdateAzureRegionAndVMSizes.ps1
  JenkinsPipelines/Scripts/UpdatePublisherImages.ps1
  Libraries/Azure.psm1
  Libraries/TestLogs.psm1
  TestControllers/AzureController.psm1
  TestProviders/AzureProvider.psm1
  Testscripts/Windows/CAPTURE-VHD-BEFORE-TEST.ps1
  Testscripts/Windows/DEPLOY-LONG-TERM-VM.ps1
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
  Testscripts/Windows/DiskHotAddRemove-Parallel.ps1
  Testscripts/Windows/DiskHotAddRemove-Serial.ps1
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-NAT.ps1
  Testscripts/Windows/NESTED-HYPERV-STORAGE-PERF.ps1
  Testscripts/Windows/NESTED-KVM-STORAGE-PERF.ps1
  Testscripts/Windows/NET-Add-NIC-After-Provision.ps1
  Testscripts/Windows/SRIOV-RUN-COMMON-TEST.ps1
  Testscripts/Windows/VERIFY-DISK-WITH-NOBARRIER.ps1
  Testscripts/Windows/VM-HOT-RESIZE.ps1
  Testscripts/Windows/dpdk-testFWD.ps1
  Testscripts/Windows/dpdk-testFailsafe.ps1
  UnitTests/PowerShell/LISAv2-Framework.Tests.ps1
  UnitTests/PowerShell/Libraries/Libraries.Azure.Tests.ps1
  UnitTests/PowerShell/TestControllers/AzureController.Tests.ps1
  Utilities/CopyVHDtoOtherStorageAccount.ps1
  Utilities/CreateServicePrincipal.ps1
  Utilities/Get-AzureVMs.ps1
  Utilities/Get-SubscriptionUsage.ps1
  Utilities/Get-SubscriptionUsageTopVMs.ps1
  Utilities/Install-CustomScript.ps1
  Utilities/ManageTestStorageAccounts.ps1
  Utilities/Remove-OldAzureVMs.ps1
  Utilities/UploadFilesToStorageAccount.ps1
  Utilities/UploadVHDtoAzureStorage.ps1
  Utilities/VmOfToday.ps1
Labels: Infra-change, PR-Verified

#319 Fix issues for sle_hpc distro
  Testscripts/Linux/DetectLinuxDistro.sh
  Testscripts/Linux/LIS-MODULES-CHECK.py
  Testscripts/Linux/VERIFY-LIS-MODULES-VERSION.sh
  Testscripts/Linux/azuremodules.py
  Testscripts/Linux/nested_vm_utils.sh
  Testscripts/Linux/perf_syscallbenchmark.sh
  Testscripts/Linux/utils.sh
Labels: PR-Verified, enhancement, 🐞 Bug

#322 SRIOV-INTERRUPTS-CHANGE - Fix test case issue against RHEL 7.5
  Testscripts/Linux/SR-IOV_Interrupts_Change.sh
Labels: PR-Verified, enhancement, 🐞 Bug

#330 FCOPY-BASIC: Refine automation
  Testscripts/Windows/FCOPY-BASIC.ps1
Labels: enhancement

#329 RELOAD-MODULES-SMP: Fix the empty argument issue
  Testscripts/Windows/RELOAD-MODULES.ps1
Labels: enhancement

#328 Modify if-statement blocks for a for-loop statement about 'grep hyperv'
  Testscripts/Linux/CORE-InitrdModulesCheck.sh
  Testscripts/Linux/CORE-LogCollector.sh
  Testscripts/Linux/RELOAD-MODULES.sh
  Testscripts/Linux/VERIFY-LIS-MODULES-VERSION.sh
Labels: enhancement

#315 Azure Deployment: get deploy fail reason from Azure
  Libraries/Azure.psm1
  Libraries/HyperV.psm1
  Libraries/TestLogs.psm1
  TestControllers/TestController.psm1
  TestProviders/AzureProvider.psm1
Labels: Infra-change, enhancement

#332 Fix test issue for TIME-CLOCKSOURCE
  Testscripts/Linux/TIME-CLOCKSOURCE.sh
Labels: enhancement

#337 WALA-VERIFY-WAAGENT-LOG - add 'latin-1' error into ignorable-walalog-errors.xml
  XML/Other/ignorable-walalog-errors.xml
Labels: enhancement

#346 WALA-VERIFY-WAAGENT-LOG - add 'name=WALinuxAgent..' error into ignorable-walalog-errors.xml
  XML/Other/ignorable-walalog-errors.xml
Labels: enhancement

#291 Azure: Enabled Azure subscription authentication using Azure context files and Manual Login
  Libraries/Azure.psm1
  TestControllers/AzureController.psm1
  Utilities/Create-AzureContextFile.ps1
Labels: PR-Verified, enhancement

#343 Azure : Added utility script to create 'Azure configuration files' for jenkins
  Utilities/Create-AzureConfigFilesForJenkins.ps1
Labels: ⚠️ PR-UNDER-TEST

#352 Add missing param nvme_version=NVME_VERSION for nvme test cases.
  XML/TestCases/FunctionalTests-NVME.xml
Labels: enhancement

#353 utils.sh: Install the most basic tools for compiling software
  Testscripts/Linux/utils.sh
Labels: enhancement

#345 LSVMBUS.sh: fix scsi controller spread check on cores
  Testscripts/Linux/LSVMBUS.sh
Labels: PR-Verified, enhancement

#359 function GetOSVersion: fix compatibility with SLES
  Testscripts/Linux/utils.sh
Labels: 🐞 Bug

#355 Fix: Handled a condition of incorrect parameter selection
  JenkinsPipelines/Run-Linux-Tests.groovy
Labels: ⚠️ PR-UNDER-TEST, 🐞 Bug

#360 RELOAD-MODULES-SMP - remove hv_utils from MODULES_NOT_TO_RELOAD.
  Testscripts/Linux/RELOAD-MODULES.sh
  Testscripts/Windows/SRIOV-RUN-COMMON-TEST.ps1
Labels: 🐞 Bug

#362 VERIFY-BOOT-ERROR-WARNINGS - add 'TLS record write failed' error into ignorable-boot-errors.xml
  XML/Other/ignorable-boot-errors.xml
Labels: 🐞 Bug

#356 LIS: Updated LIS versions in Replaceable XML
  XML/Other/ReplaceableTestParameters.xml
Labels: PR-Verified, 🐞 Bug

#316 Azure: Added linux boot time telemetry
  Libraries/Azure.psm1
  Libraries/Database.psm1
  TestControllers/AzureController.psm1
  TestProviders/AzureProvider.psm1
  Testscripts/Linux/CollectLogFile.sh
  XML/Other/text-identifiers.xml
Labels: PR-Verified

#366 NETWORK.ETHTOOL: Skip Get/Set msg level test if kernel symbols missing
  Testscripts/Linux/ETHTOOL-MSG-LEVEL.sh
Labels: PR-Verified

#364 HyperV - Make sure that SRIOV is enabled after test
  Testscripts/Windows/SRIOV-DISABLE-NIC.ps1
  Testscripts/Windows/SRIOV-DISABLEVF-ONHOST.ps1
Labels: 🐞 Bug

#373 TIME-CLOCKSOURCE - Add a loop about "sleep 10 seconds" for message show up in log file
  Testscripts/Linux/TIME-CLOCKSOURCE.sh
Labels: enhancement

#372 KVP-BASIC-CHECKS - Modify the result of the KVP test to skip when daemon is not running by default
  Testscripts/Linux/KVP-BasicChecks.sh
Labels: 🐞 Bug

#376 Run-Linux-Tests.groovy: fix non-ascii characters
  JenkinsPipelines/Run-Linux-Tests.groovy
Labels: 🐞 Bug

#369 SRIOV: Assign a broadcast address
  Testscripts/Linux/SR-IOV-Utils.sh
Labels: PR-Verified, enhancement

#368 SRIOV-VERIFY-MAX-VF-CONNECTION-MAX-VCPU: stabilize test-case
  Testscripts/Linux/SRIOV-VerifyVF-Connection.sh
Labels: PR-Verified, enhancement

#381 Hyper-V: Framework improvements
  Libraries/HyperV.psm1
  TestProviders/HyperVProvider.psm1
Labels: PR-Verified, enhancement

#379 xfstests: Added CIFS Azure Files TC
  Testscripts/Linux/xfstesting.sh
  Testscripts/Windows/FILE-SYSTEM-VERIFICATION-TESTS.ps1
  XML/TestCases/CommunityTests.xml
Labels: PR-Verified, enhancement

#374 VERIFY-LINUX-DISK-SETUP - RedHat RHEL 7-LVM 7.6.2019060521
  Testscripts/Linux/VERIFY-LINUX-DISK-SETUP.py
Labels: 🐞 Bug
