Repository microsoft/lisa, pull requests merged in 2019-07, with the labels that each got.

#375 Dpdk primary secondary process
  Libraries/CommonFunctions.psm1
  Testscripts/Linux/build_install_rdma_core.sh
  Testscripts/Linux/dpdk_verify_primary_secondary.sh
  Testscripts/Windows/VERIFY-DPDK-PRIMARY-SECONDARY-PROCESSES.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-DPDK.xml
Labels: enhancement

#384 Azure: Recognize a boot failure if the '(initramfs)' appears in the b…
  Libraries/Azure.psm1
Labels: enhancement

#385 dpdk: fix primary/secondary TC skip
  Testscripts/Windows/VERIFY-DPDK-PRIMARY-SECONDARY-PROCESSES.ps1
Labels: enhancement

#388 function add_sles_benchmark_repo: update repo for sles12sp4
  Testscripts/Linux/utils.sh
Labels: ⚠️ PR-UNDER-TEST

#390 VERIFY-DEPLOYMENT-PROVISION-EPHEMERAL-MANAGED-DISK: update vm size
  XML/TestCases/FunctionalTests.xml
Labels: PR-Verified

#389 Use yum clean all to refresh repos, makecache uses too much space
  Testscripts/Linux/utils.sh
Labels: PR-Verified, 🐞 Bug

#378 PartitionDisks.sh: Skip the OS disk
  Testscripts/Linux/PartitionDisks.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/PRODUCTION-CHECKPOINT-PARTITION.ps1
Labels: ⚠️ PR-UNDER-TEST, 🛑 DO-NOT-MERGE

#398 Mark GPU test results fail if one of sub-result fail.
  Testscripts/Windows/GPU-DRIVER-INSTALL.ps1
Labels: enhancement

#397 Update RDMA cases use consistent size.
  XML/TestCases/FunctionalTests-InfiniBand.xml
Labels: enhancement

#400 Skip GPU and RDMA tests against COREOS and CLEARLINUX distro.
  Testscripts/Windows/GPU-DRIVER-INSTALL.ps1
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
Labels: enhancement

#404 Jenkins: Fixed an issue where HyperV tests were listed in Azure platform
  JenkinsPipelines/Scripts/JenkinsTestSelectionMenuGenerator.ps1
Labels: PR-Verified, 🐞 Bug

#399 Fix test case issue - VERIFY-LINUX-DISK-SETUP
  Testscripts/Linux/VERIFY-LINUX-DISK-SETUP.py
  Testscripts/Linux/azuremodules.py
Labels: enhancement

#401 PRODUCTION-CHECKPOINT-PARTITION.ps1: Traverse all disks combination
  Testscripts/Windows/PRODUCTION-CHECKPOINT-PARTITION.ps1
Labels: enhancement

#411 Fix install linux-perf_[version].deb issue against debian 8.11 in msft pipeline.
  Testscripts/Linux/customKernelInstall.sh
Labels: 🐞 Bug

#410 Fix test issue for VERIFY-DPDK-VPP
  Testscripts/Linux/build_test_vpp.sh
Labels: dpdk, enhancement

#420 INFINIBAND-OPEN-MPI-2VM - Find a right way for mpirun
  Testscripts/Linux/TestRDMA_MultiVM.sh
Labels: 🐞 Bug

#405 nvme_blkdiscard.sh: Added skip check for ubuntu_14.04
  Testscripts/Linux/nvme_blkdiscard.sh
  Testscripts/Linux/utils.sh
Labels: PR-Verified

#422 KDUMP-Config.sh: Fix broken package on ubuntu
  Testscripts/Linux/KDUMP-Config.sh
Labels: enhancement

#413 RELOAD-MODULES-SMP - Add a loop about 'sleep 3 seconds' for get eth0 ip
  Testscripts/Linux/RELOAD-MODULES.sh
Labels: 🐞 Bug

#406 Fix KDUMP + NVME test issues against Ubuntu 14.04
  Testscripts/Linux/KDUMP-Config.sh
  Testscripts/Linux/utils.sh
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests.xml
Labels: PR-Verified, enhancement

#415 GPU: Limit the batch size based on test mode
  Testscripts/Linux/gpu-tensorflow.sh
Labels: enhancement

#423 INFINIBAND-OPEN-MPI-2VM - Mark INFINIBAND test results fail if one of sub-result fail.
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
Labels: enhancement

#425 Fix issue when there is no dependency VM.
  Testscripts/Windows/SRIOV-RUN-COMMON-TEST.ps1
Labels: 🐞 Bug

#309 dpdk: fix for testpmd new incompatibility
  Testscripts/Linux/dpdkUtils.sh
Labels: PR-Verified, 🐞 Bug

#424 GPU: Refactor log collection; Collect test logs after driver install fail
  Libraries/CommonFunctions.psm1
  Libraries/TestLogs.psm1
  Testscripts/Linux/gpu-driver-install.sh
  Testscripts/Windows/GPU-DRIVER-INSTALL.ps1
Labels: PR-Verified, enhancement

#421 STRESSTEST-RELOAD-LIS-MODULES - 'Canonical UbuntuServer 16.04-LTS latest'
  Testscripts/Windows/RELOAD-MODULES.ps1
Labels: enhancement

#428 STORAGE-HOT-ADD-DISK-SERIAL - potential fix test case issue
  Testscripts/Windows/DiskHotAddRemove-Serial.ps1
Labels: PR-Verified, 🐞 Bug

#430 Automatic trimming of TestNames and ARMImageName
  Run-LisaV2.ps1
Labels: enhancement

#435 FILE-SYSTEM-VERIFICATION-TESTS: handle better vm connection check
  Testscripts/Windows/FILE-SYSTEM-VERIFICATION-TESTS.ps1
Labels: enhancement

#434 VERIFY-DPDK-FAILSAFE-DURING-TRAFFIC - fix perf results TestMode and TestCaseName
  Testscripts/Linux/dpdk-testFailsafe.sh
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
  XML/TestCases/FunctionalTests-DPDK.xml
Labels: 🐞 Bug

#439 Kdump cases: fix distro detect for 6.X and 7.X versions
  Testscripts/Linux/KDUMP-Config.sh
Labels: 🐞 Bug

#444 VERIFY-BOOT-ERROR-WARNINGS - add warnings into ignorable-boot-errors.xml
  XML/Other/ignorable-boot-errors.xml
Labels: 🐞 Bug

#445 STORAGE-HOT-ADD-DISK-PARALLEL - potential fix test case issue
  Testscripts/Windows/DiskHotAddRemove-Parallel.ps1
Labels: enhancement

#426 LIS-PREINSTALL-DISK-SIZE-VERIFICATION: Skip test if LIS does not support kernel version
  Testscripts/Linux/Test_LIS_disk_check.sh
Labels: enhancement

#451 Remove extra output when check MellanoxAdapter.
  Libraries/CommonFunctions.psm1
Labels: 🐞 Bug

#446 utils.sh: Update the get_OSdisk function to support more distro
  Testscripts/Linux/utils.sh
Labels: enhancement

#449 Update lagscope build steps
  Testscripts/Linux/perf_lagscope.sh
  Testscripts/Linux/utils.sh
Labels: PR-Verified, 🐞 Bug

#440 Azure: Fixed the captured VHD name
  TestControllers/TestController.psm1
  Testscripts/Windows/CAPTURE-VHD-BEFORE-TEST.ps1
Labels: PR-Verified, 🐞 Bug

#455 SRIOV test cases: Add -runAsSudo option to run linux command
  Testscripts/Windows/SETUP-SR-IOV-Configure.ps1
  Testscripts/Windows/SRIOV-CHANGE-RSS.ps1
  Testscripts/Windows/SRIOV-DETACH-NIC.ps1
  Testscripts/Windows/SRIOV-DISABLE-NIC.ps1
  Testscripts/Windows/SRIOV-DISABLE-VMQ.ps1
Labels: 🐞 Bug

#454 Perf Storage RAID0: Create array from unmounted disks not disk letters (c-z)
  Testscripts/Linux/perf_fio.sh
Labels: PR-Verified

#457 VERIFY-DEPLOYMENT-PROVISION: Add optional vCpu count check
  Testscripts/Windows/VERIFY-DEPLOYMENT-PROVISION.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests.xml
Labels: PR-Verified

#456 Add initial and final kernel version to Test Summary
  Libraries/CommonFunctions.psm1
  Libraries/TestReport.psm1
  TestControllers/TestController.psm1
Labels: enhancement

#431 Support delete OS disk and Data disk when delete VM
  Utilities/Remove-OldAzureVMs.ps1
Labels: enhancement

#461 Azure resource usage monitor : Added File size monitoring
  Utilities/Get-SubscriptionUsage.ps1
Labels: Feature-Request, PR-Verified, enhancement

#442 Utilities : Added storage cleanup script
  Utilities/Cleanup-AzureStorageAccounts.ps1
Labels: Feature-Request, PR-Verified, enhancement

#459 Skip DPDK tests against SLES12.
  Libraries/CommonFunctions.psm1
Labels: dpdk, enhancement

#462 FILE-SYSTEM-VERIFICATION-TESTS: Get disk from azure scsi devices, not hard-coded.
  Testscripts/Linux/xfstesting.sh
  XML/TestCases/CommunityTests.xml
Labels: PR-Verified

#463 Fix NET-BOOT-NONIC-HOT-ADD-NIC test case issue and remove redundant invoke of Detect-LinuxDistro
  Testscripts/Windows/GPU-TENSORFLOW.ps1
  Testscripts/Windows/NET-Boot-NoNIC-HotAdd-NIC.ps1
  Testscripts/Windows/STRESS-Web.ps1
  Testscripts/Windows/VERIFY-VHD-PREREQUISITES.ps1
Labels: enhancement

#464 Ubuntu fix broken package
  Testscripts/Linux/utils.sh
Labels: enhancement

#465 RDMA IB: Added RHEL 8.x / CentOS 8.x support
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
Labels: enhancement

#471 To set custom parameter OSType for deploy VM in JSON file
  Libraries/Azure.psm1
Labels: ❓ Question

#470 SRIOV-VerifyVF-Connection.sh: Use absolute path to send file
  Testscripts/Linux/SRIOV-VerifyVF-Connection.sh
Labels: enhancement

#478 Fix Socket.Connect Exception and ambiguous overload
  Libraries/TestHelpers.psm1
Labels: 🐞 Bug

#475 Fix install lagscope in ntttcp testing.
  Testscripts/Linux/perf_lagscope.sh
  Testscripts/Linux/utils.sh
Labels: enhancement

#476 INFINIBAND-OPEN-MPI-2VM - Find a right way for mpirun about distro sle_hpc
  Testscripts/Linux/TestRDMA_MultiVM.sh
Labels: 🐞 Bug

#474 SRIOV test: Disable the NetworkManager
  Testscripts/Linux/SR-IOV-Utils.sh
  Testscripts/Windows/SETUP-SR-IOV-Configure.ps1
Labels: enhancement

#482 Install ethtool with common function
  Testscripts/Linux/utils.sh
Labels: enhancement

#479 NET-IFUP-IFDOWN: Fix waiting for SSH during test, new ip would get value 'False'
  Testscripts/Windows/NET-IFUP-IFDOWN.ps1
Labels: PR-Verified

#484 STOR-VHDX-RESIZE-GROWFS.ps1: Get OS disk with common function
  Testscripts/Linux/utils.sh
  Testscripts/Windows/STOR-VHDX-RESIZE-GROWFS.ps1
Labels: enhancement

#485 Modify function Get-IPv4AndWaitForSSHStart 'False' to be 'null'
  Libraries/IntegrationServiceLibrary.psm1
Labels: enhancement

#486 RDMA IB: Added HPC-X support for Ubuntu and SLES
  Testscripts/Linux/SetupRDMA.sh
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
Labels: PR-Verified, enhancement, rdma

#489 NVIDIA-CUDA-DRIVER-VALIDATION: Temporary fix for ubuntu 19.04
  Testscripts/Linux/gpu-driver-install.sh
Labels: enhancement
