Repository microsoft/lisa, pull requests merged in 2019-11, with the labels that each got.

#617 Hyper-V: minor update LIS-Mount-CD to support run remotely and clean iso file
  Testscripts/Windows/LIS-Mount-CD.ps1
  Testscripts/Windows/SETUP-RemoveIsoFromDvd.ps1
  XML/TestCases/FunctionalTests.xml
Labels: enhancement

#619 Call DetectLinuxDistro with bash explicitly
  Libraries/CommonFunctions.psm1
Labels: enhancement

#621 Fix issue met in KDUMP area.
  Libraries/TestHelpers.psm1
Labels: enhancement

#622 Fix test issue when run testing against Ubuntu 19.10 (EOAN)
  Testscripts/Linux/CORE-InitrdModulesCheck.sh
  Testscripts/Linux/Linux-Test-Project-Tests.sh
  Testscripts/Linux/SRIOV-Iperf-Stress.sh
  Testscripts/Linux/stress_web.sh
  Testscripts/Linux/utils.sh
  Testscripts/Linux/xfstesting.sh
  Testscripts/Windows/DM_HotAddRemove.ps1
  Testscripts/Windows/FILE-SYSTEM-VERIFICATION-TESTS.ps1
  Testscripts/Windows/SRIOV-DISABLEVF-IPERF.ps1
  Testscripts/Windows/SRIOV-DISABLEVF-ONHOST.ps1
  XML/Other/ReplaceableTestParameters.xml
Labels: enhancement

#623 Fix test issues against CentOS 8.0 and Redhat 8.0
  Testscripts/Linux/KDUMP-Config.sh
  Testscripts/Linux/KDUMP-Execute.sh
  Testscripts/Linux/LSVMBUS.sh
  Testscripts/Linux/VERIFY-VHD-PREREQUISITES.py
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Linux/gpu-driver-install.sh
  Testscripts/Linux/nested_vm_utils.sh
  Testscripts/Linux/utils.sh
  Testscripts/Linux/xfstesting.sh
Labels: 🐞 Bug

#625 Add option for installing OFED from extension.
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
Labels: enhancement

#624 Add custom timeout parameter in Install-CustomScript.ps1
  Utilities/Install-CustomScript.ps1
Labels: enhancement

#626 Fix issue in RHEL 8 about missing install package kernel-modules-extra
  Testscripts/Linux/NET-Corruption.sh
Labels: enhancement

#629 Added new test case of NVMe long-term stress test
  Testscripts/Linux/nested_kvm_perf_fio.sh
  Testscripts/Linux/perf_fio.sh
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/StressTests.xml
Labels: PR-Verified

#627 GPU count calculation correction
  Testscripts/Linux/gpu-driver-install.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/GPU-DRIVER-INSTALL.ps1
Labels: PR-Verified

#633 Fix nested test cases.
  Testscripts/Linux/nested_hyperv_ntttcp_different_l1_nat.sh
  Testscripts/Linux/nested_hyperv_ntttcp_different_l1_public_bridge.sh
  Testscripts/Linux/nested_kvm_basic_test.sh
  Testscripts/Linux/nested_kvm_lagscope_different_l1_public_bridge.sh
  Testscripts/Linux/nested_kvm_netperf_pps.sh
  Testscripts/Linux/nested_kvm_netperf_pps_nat.sh
  Testscripts/Linux/nested_kvm_ntttcp_different_l1_nat.sh
  Testscripts/Linux/nested_kvm_ntttcp_different_l1_public_bridge.sh
  Testscripts/Linux/nested_kvm_ntttcp_private_bridge.sh
  Testscripts/Linux/nested_kvm_storage_perf.sh
  Testscripts/Linux/nested_vm_utils.sh
  Testscripts/Windows/NESTED-KVM-NTTTCP-PRIVATE-BRIDGE.ps1
  XML/TestCases/NestedVmTests.xml
Labels: 🐞 Bug

#638 Fix typo about bash file name "NET-Max-NICs.sh"
  Testscripts/Windows/NET-HotAddRemove-Max-NIC.ps1
  XML/TestCases/FunctionalTests-Network.xml
Labels: 🐞 Bug

#639 Fix test issue in storage area.
  Testscripts/Windows/DiskHotAddRemove-Parallel.ps1
  Testscripts/Windows/DiskHotAddRemove-Serial.ps1
  Testscripts/Windows/VERIFY-DISK-WITH-NOBARRIER.ps1
Labels: 🐞 Bug

#642 Add checking publisher when sed grub configration
  Testscripts/Linux/customKernelInstall.sh
Labels: 🐞 Bug

#637 Modeprobe_Setup: Ubuntu needs manual loading for mlx4 driver
  Testscripts/Linux/dpdkUtils.sh
Labels: dpdk

#643 Print OverrisdeVMSize, if exists
  Libraries/TestReport.psm1
  TestControllers/TestController.psm1
Labels: PR-Verified, enhancement

#645 Install net-tools on eoan
  Testscripts/Linux/utils.sh
Labels: 🐞 Bug

#644 Adding clear logging including debug info (GPU)
  Testscripts/Linux/gpu-driver-install.sh
  Testscripts/Linux/gpu-tensorflow.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/GPU-DRIVER-INSTALL.ps1
  Testscripts/Windows/GPU-TENSORFLOW.ps1
Labels: PR-Verified

#646 Fix hung issue when invoke start-azvm in pipeline.
  Libraries/Azure.psm1
Labels: PR-Verified, enhancement

#648 Fix indent and clean up LIS for following cases.
  Testscripts/Windows/LIS-INSTALL-SCENARIOS.ps1
Labels: enhancement

#650 Startup memory 512M is too low, cause VM enter into OOM status, increase it into 1024M
  Testscripts/Linux/customKernelInstall.sh
  XML/TestCases/FunctionalTests-DynamicMemory.xml
Labels: enhancement

#651 Harz/ready doc and db
  Documents/How-to-use.md
  LISAv2-Framework.psm1
  Libraries/Database.psm1
  README.md
  Run-LisaV2.ps1
Labels: enhancement
