Repository microsoft/lisa, pull requests merged in 2019-04, with the labels that each got.

#72 Ubuntu: fix BVT-CORE-TIMESYNC-NTP install dependencies v2
  Testscripts/Linux/BVT-CORE-TIMESYNC-NTP.sh
  Testscripts/Linux/utils.sh
Labels: PR-Verified, enhancement

#74 Update nested perf storage and perf storage test use new model insert database
  Testscripts/Linux/nested_kvm_perf_fio.sh
  Testscripts/Linux/perf_fio_nfs.sh
  Testscripts/Windows/NESTED-HYPERV-STORAGE-PERF.ps1
  Testscripts/Windows/NESTED-KVM-STORAGE-PERF.ps1
  Testscripts/Windows/PERF-NETWORK-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
  Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
  Testscripts/Windows/PERF-STORAGE-OVER-NFS.ps1
  XML/TestCases/PerformanceTests.xml
Labels: PR-Verified, enhancement

#80 Add a new test case of rescind the VF device from guest
  Testscripts/Linux/SRIOV-Hotplug-VF-Device.sh
  XML/TestCases/FunctionalTests-SRIOV.xml
Labels: ⚠️ PR-UNDER-TEST

#84 LTP: Use vhdx test disk instead of vhd
  Testscripts/Linux/Linux-Test-Project-Tests.sh
  XML/TestCases/CommunityTests.xml
Labels: PR-Verified

#87 BVT-CORE-RELOAD-MODULES-SMP: Fix issue against CentOS
  Testscripts/Linux/BVT-CORE-RELOAD-MODULES.sh
  Testscripts/Windows/BVT-CORE-RELOAD-MODULES.ps1
Labels: PR-Verified, 🐞 Bug

#82 Stable nested perf storage test cases (L1 is windows OS)
  Testscripts/Windows/NESTED-HYPERV-STORAGE-PERF.ps1
Labels: 🐞 Bug

#81 Add two columns NumberOfReceivers and NumberOfSenders in database to distinguish mode of ntttcp.
  Testscripts/Windows/PERF-NETWORK-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
Labels: enhancement

#88 Change the restart way for try to work around when hit 404 issue on Azure.
  TestProviders/AzureProvider.psm1
Labels: Infra-change, enhancement

#83 Increase vm alive retry count to allow longer network setup in the VM after boot
  Libraries/CommonFunctions.psm1
Labels: Infra-change, enhancement, ⚠️ PR-UNDER-TEST

#86 Fix custom kernel install
  Libraries/Azure.psm1
  Libraries/CommonFunctions.psm1
  Testscripts/Linux/customKernelInstall.sh
Labels: Infra-change, PR-Verified, enhancement, 🐞 Bug

#92 Hyper-V: VM Automatic stop action - Shutdown
  Libraries/HyperV.psm1
Labels: Infra-change, PR-Verified, enhancement

#96 dpdk: add support for centos/rhel 7.6
  Testscripts/Linux/dpdkSetupAndRunTest.sh
  Testscripts/Linux/dpdkUtils.sh
Labels: ⚠️ PR-UNDER-TEST, 🐞 Bug

#99 dpdk: do not install rdma core on ubuntu 16.04
  Testscripts/Linux/dpdkUtils.sh
Labels: enhancement

#97 Update KVP-TestRescind.ps1 to fix Get-VMFeatureSupport function
  Libraries/CommonFunctions.psm1
  Testscripts/Windows/KVP-TestRescind.ps1
Labels: 🐞 Bug

#101 Update LSVMBUS.sh
  Testscripts/Linux/LSVMBUS.sh
Labels: 🐞 Bug

#100 dpdk: added perf data to TC summary + centos fixes
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
Labels: enhancement

#98 SR-IOV, NVMe: Rescind PCI device test
  Testscripts/Linux/SRIOV-Hotplug-VF-Device.sh
  Testscripts/Linux/SRIOV-VerifyVF-Connection.sh
  Testscripts/Linux/nvme_basic_validation.sh
  Testscripts/Linux/utils.sh
  XML/TestCases/FunctionalTests-NVME.xml
  XML/TestCases/FunctionalTests-SRIOV.xml
Labels: enhancement, ⚠️ PR-UNDER-TEST

#102 DPDK: New TC VERIFY-DPDK-RING-LATENCY
  Testscripts/Linux/run_dpdk_ring_latency.sh
  Testscripts/Windows/VERIFY-DPDK-RING-LATENCY.ps1
  XML/TestCases/FunctionalTests-DPDK.xml
Labels: enhancement, ⚠️ PR-UNDER-TEST

#103 Update the version of tensorflow
  Testscripts/Linux/gpu-tensorflow.sh
  XML/Other/ReplaceableTestParameters.xml
Labels: PR-Verified, 🐞 Bug

#105 Fix LSVMBUS test case for big VM sizes
  Testscripts/Linux/LSVMBUS.sh
Labels: PR-Verified, 🐞 Bug

#104 New Azure TC: Add NIC after VM Provision
  Testscripts/Windows/NET-Add-NIC-After-Provision.ps1
  XML/TestCases/FunctionalTests-Network.xml
Labels: PR-Verified, enhancement

#106 LISAv2: implement multiple override vm sizes
  README.md
  TestControllers/TestController.psm1
Labels: enhancement

#110 GPU: Added rescind for PCI device
  Testscripts/Linux/utils.sh
  Testscripts/Windows/GPU-DRIVER-INSTALL.ps1
  XML/TestCases/FunctionalTests-GPU.xml
Labels: PR-Verified

#112 CPU: Azure L3 cache spread
  Testscripts/Linux/L3Cache-Verify.sh
  XML/TestCases/FunctionalTests.xml
Labels: PR-Verified

#114 BVT tests location reorg
  Testscripts/Linux/NET-IFUP-IFDOWN.sh
  Testscripts/Linux/RELOAD-MODULES.sh
  Testscripts/Linux/VERIFY-LIS-MODULES-VERSION.sh
  Testscripts/Linux/VERIFY-LIS-MODULES.sh
  Testscripts/Windows/BVT-VERIFY-KVP-DAEMON-STATUS.ps1
  Testscripts/Windows/NET-IFUP-IFDOWN.ps1
  Testscripts/Windows/RELOAD-MODULES.ps1
  XML/TestCases/BVT.xml
  XML/TestCases/FunctionalTests-Network.xml
  XML/TestCases/FunctionalTests-WALA.xml
  XML/TestCases/FunctionalTests.xml
Labels: ⚠️ PR-UNDER-TEST, 🛑 DO-NOT-MERGE

#116 Fixed the GPU Test summary issue
  Testscripts/Windows/GPU-DRIVER-INSTALL.ps1
Labels: PR-Verified, 🐞 Bug

#115 Fix uptime -s issue, fix empty test case name when ResultDBTestTag is not set, add column to distinguish storage type for storage perf test
  Testscripts/Linux/CollectLogFile.sh
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-NAT.ps1
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-HYPERV-STORAGE-PERF.ps1
  Testscripts/Windows/NESTED-KVM-LAGSCOPE-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-NETPERF-PPS.ps1
  Testscripts/Windows/NESTED-KVM-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-STORAGE-PERF.ps1
  Testscripts/Windows/PERF-GOLANG-BENCHMARK.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-NETPERF.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-SINGLE-CONNECTION-THROUGHPUT.ps1
  Testscripts/Windows/PERF-NETWORK-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
  Testscripts/Windows/PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-IPERF3.ps1
  Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
  Testscripts/Windows/PERF-STORAGE-OVER-NFS.ps1
  Testscripts/Windows/PERF-SYSCALL-BENCHMARK.ps1
Labels: enhancement, 🐞 Bug

#119 PCI Passthrough: fix to allow multiple devices
  Testscripts/Linux/utils.sh
Labels: PR-Verified

#120 Fix dpdk sriov failsafe and fail DPDK ring instead of abort
  Libraries/Azure.psm1
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Linux/run_dpdk_ring_latency.sh
  XML/TestCases/FunctionalTests-DPDK.xml
Labels: ⚠️ PR-UNDER-TEST, 🐞 Bug

#129 BVT consolidation - part 3
  Documents/Azure BVT automation/BVT-IS-ROOT-PASSWORD-DELETED.txt
  Documents/Azure BVT automation/BVT-ROOT-DEVICE-TIMEOUT-CHECK.txt
  Documents/Azure BVT automation/BVT-SWAP-CHECK.txt
  Documents/Azure BVT automation/BVT-VERIFY-UUID-FSTAB.txt
  Testscripts/Linux/BVT-IS-ROOT-PASSWORD-DELETED.py
  Testscripts/Linux/BVT-LAST-CONSOLE-CHECK.py
  Testscripts/Linux/BVT-MTAB-ENTRY-CHECK.py
  Testscripts/Linux/BVT-ROOT-DEVICE-TIMEOUT-CHECK.py
  Testscripts/Linux/BVT-SWAP-CHECK.py
  Testscripts/Linux/BVT-VERIFY-BASH-HISTORY.py
  Testscripts/Linux/BVT-VERIFY-SSHD-CONFIG.py
  Testscripts/Linux/BVT-VERIFY-UUID-FSTAB.py
  Testscripts/Linux/VERIFY-LINUX-CONFIGURATION.py
  Testscripts/Linux/VERIFY-LINUX-DISK-SETUP.py
  Testscripts/Windows/BVT-VERIFY-SSHD-CONFIG.ps1
  XML/TestCases/BVT.xml
  XML/TestCases/FunctionalTests.xml
Labels: enhancement

#135 RDMA IB: Various fixes and improvements
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
Labels: PR-Verified, enhancement, 🐞 Bug

#146 Update customKernelInstall.sh
  Testscripts/Linux/customKernelInstall.sh
Labels: PR-Verified

#141 Intel Benchmark P2P support
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
Labels: Approved, PR-Verified, enhancement

#145 RELOAD-MODULES: Fix missing rename part
  Documents/Utility-Script-Example.md
  XML/TestCases/StressTests.xml
Labels: PR-Verified, 🐞 Bug

#149 dpdk: add support for .gz dpdk sources
  Testscripts/Linux/dpdkUtils.sh
Labels: 🐞 Bug

#150 Hyper-V cleanup: Decreased times
  Utilities/Remove-OldHypervVMs.ps1
Labels: PR-Verified

#153 RDMA: Remove mpi-benchmark installation in Intel MPI
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
  XML/Other/ReplaceableTestParameters.xml
Labels: Approved, PR-Verified

#155 Update for refer undefined parameter
  Libraries/Azure.psm1
Labels: 🐞 Bug

#158 SR-IOV: Add Mlnx CX4 support for HyperV; SLES: Firewall check fix
  Testscripts/Linux/SR-IOV-Utils.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/SRIOV-CHANGE-RSS.ps1
  Testscripts/Windows/SRIOV-DETACH-NIC.ps1
  Testscripts/Windows/SRIOV-DISABLE-NIC.ps1
  Testscripts/Windows/SRIOV-DISABLE-VMQ.ps1
Labels: PR-Verified

#154 LISAv2: update test-cases priority
  Documents/Azure BVT automation/1.How-To-Start-BVT-Cycle.txt
  Documents/Azure BVT automation/BVT-HVMODULES-CHECK.txt
  Documents/Azure BVT automation/BVT-RESOURCE-DISK-FILESYSTEM.txt
  Documents/Azure BVT automation/BVT-VERIFY-BOOT-ERROR-WARNINGS.txt
  Documents/Azure BVT automation/BVT-VERIFY-DEPLOYMENT-PROVISION.txt
  Documents/Azure BVT automation/BVT-VERIFY-DISKSIZE.txt
  Documents/Azure BVT automation/BVT-VERIFY-FIREWALL-STATUS.txt
  Documents/Azure BVT automation/BVT-VERIFY-HOSTNAME.txt
  Documents/Azure BVT automation/BVT-VERIFY-MNT-RESOURCE-WRITABLE.txt
  Documents/Azure BVT automation/BVT-VERIFY-RESTART.txt
  Documents/Azure BVT automation/BVT-VERIFY-SHUTDOWN.txt
  Documents/Azure BVT automation/BVT-WA-PROC-CHECK.txt
  Documents/Azure BVT automation/BVT-WA-VER-CHECK.txt
  Documents/Azure Network automation/1.How-To-Start-NETWORK-Cycle.txt
  Documents/Azure VNET automation/1.How-To-Start-VNET-Cycle.txt
  Documents/Azure VNET automation/CONFIGURE-VNET-DNS-SERVER.txt
  Documents/Azure VNET automation/SETUP-TEST-ENVIRONMENT.txt
  Documents/Azure VNET automation/VNET-IPERF-UDP-INTRAVNET-ACCESS.txt
  Documents/Azure VNET automation/VNET-IPERF-UDP-LOCAL-TO-VNET-ACCESS.txt
  Documents/Azure VNET automation/VNET-IPERF-UDP-OUTBOUND-ACCESS.txt
  Documents/Azure VNET automation/VNET-IPERF-UDP-VNET-TO-LOCAL-ACCESS.txt
  Documents/Azure VNET automation/VNET-PING-INTRAVNET-ACCESS.txt
  Documents/Azure VNET automation/VNET-PING-LOCAL-TO-VNET-ACCESS.txt
  Documents/Azure VNET automation/VNET-PING-OUTBOUND-ACCESS.txt
  Documents/Azure VNET automation/VNET-PING-VNET-TO-LOCAL-ACCESS.txt
  Documents/Azure VNET automation/VNET-VERIFY-CA-AFTER-INITIAL-DEPLOYMENT.txt
  Documents/Azure VNET automation/VNET-VERIFY-DNS-SERVER-IN-RESOLV-CONF.txt
  Documents/Azure VNET automation/VNET-VERIFY-GATEWAY-IP.txt
  Documents/Azure VNET automation/VNET-VERIFY-REMOTE-SSH-SCP-INTRAVNET-ACCESS.txt
  Documents/Azure VNET automation/VNET-VERIFY-REMOTE-SSH-SCP-LOCAL-TO-VNET-ACCESS.txt
  Documents/Azure VNET automation/VNET-VERIFY-REMOTE-SSH-SCP-OUTBOUND-ACCESS.txt
  Documents/How-to-use.md
  Libraries/TestReport.psm1
  README.md
  Run-LisaV2.ps1
  Testscripts/Linux/BVT-PASSWD-POLICY-TEST.py
  Testscripts/Linux/BVT-VERIFY-DISKSIZE.py
  Testscripts/Linux/BVT-VERIFY-MNT-RESOURCE-README.py
  Testscripts/Linux/VERIFY-BOOT-ERROR-WARNINGS.py
  Testscripts/Windows/BVT-VERIFY-DISKSIZE.ps1
  Testscripts/Windows/BVT-VERIFY-PRIVATEKEY-AUTHENTICATION.ps1
  XML/TestCases/BVT.xml
  XML/TestCases/FunctionalTests-DPDK.xml
  XML/TestCases/FunctionalTests-GPU.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
  XML/TestCases/FunctionalTests-NVME.xml
  XML/TestCases/FunctionalTests-Network.xml
  XML/TestCases/FunctionalTests-WALA.xml
  XML/TestCases/FunctionalTests.xml
  XML/TestCases/NestedVmTests.xml
  XML/TestCases/PerformanceTests.xml
  XML/TestCases/StressTests.xml
Labels: Approved, PR-Verified

#160 Fix two issues
  Testscripts/Linux/CollectLogFile.sh
  Testscripts/Linux/VERIFY-VHD-PREREQUISITES.py
Labels: PR-Verified, enhancement, 🐞 Bug

#157 SR-IOV: XML refresh
  Testscripts/Linux/NET-Max-NICs.sh
  Testscripts/Linux/verify-ifup-nics.sh
  Testscripts/Windows/SETUP-NET-Add-Max-NIC.ps1
  XML/TestCases/FunctionalTests-Network.xml
  XML/TestCases/FunctionalTests-SRIOV.xml
Labels: PR-Verified, enhancement

#161 Remove save global config file
  TestControllers/AzureController.psm1
  TestControllers/HyperVController.psm1
  TestControllers/TestController.psm1
  TestControllers/WSLController.psm1
Labels: PR-Verified, enhancement

#165 Change for collect total number of run cases
  TestControllers/TestController.psm1
Labels: PR-Verified, enhancement

#163 Revert set default priority, since using -TestPriority 1 will include unexpected cases
  Libraries/CommonFunctions.psm1
Labels: enhancement

#164 Remove offset for crashkernel parameter.
  XML/TestCases/FunctionalTests.xml
Labels: PR-Verified, enhancement

#166 Adjust test case sequence.
  XML/TestCases/FunctionalTests.xml
Labels: enhancement

#167 customLISInstall.sh: Multiple fixes
  Testscripts/Linux/customLISInstall.sh
Labels: PR-Verified, 🐞 Bug

#162 Update the version of LTP and prerequisites of test
  Testscripts/Linux/Linux-Test-Project-Tests.sh
  Testscripts/Windows/Run-LtpSuite.ps1
  XML/Other/ReplaceableTestParameters.xml
Labels: PR-Verified, enhancement
