Repository microsoft/lisa, pull requests merged in 2019-05, with the labels that each got.

#159 New TC: LIS-PREINSTALL-DISK-SIZE-VERIFICATION
  Testscripts/Linux/Test_LIS_disk_check.sh
  Testscripts/Linux/utils.sh
  XML/TestCases/FunctionalTests.xml
Labels: PR-Verified

#181 Remove-OldHypervVM.ps1 fix
  Utilities/Remove-OldHypervVMs.ps1
Labels: PR-Verified, 🐞 Bug

#174 Disable-Enable-PCI: add generic test script and test case for 10 nvme + 7 SR-IOV NICs
  Testscripts/Linux/SRIOV-VerifyVF-Connection.sh
  Testscripts/Linux/disableEnablePci.sh
  Testscripts/Linux/nvme_basic_validation.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/GPU-DRIVER-INSTALL.ps1
  XML/TestCases/FunctionalTests-GPU.xml
  XML/TestCases/FunctionalTests-NVME.xml
  XML/TestCases/FunctionalTests-SRIOV.xml
  XML/TestCases/FunctionalTests.xml
Labels: enhancement

#183 dpdk: fix rx forwarder
  Testscripts/Linux/dpdk-testFWD.sh
  Testscripts/Linux/dpdk-testFailsafe.sh
  Testscripts/Linux/dpdk-testPMD.sh
  Testscripts/Linux/dpdkUtils.sh
Labels: PR-Verified, 🐞 Bug

#179 Add platform info in junit file.
  TestControllers/TestController.psm1
Labels: enhancement

#182 RDMA: Added SKIPPED state for Ubuntu versions <18
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
Labels: enhancement

#188 Extend execution time for case NESTED-KVM-BASIC-VERIFICATION
  XML/TestCases/NestedVmTests.xml
Labels: enhancement

#186 dpdk: fix remaining tests after testpmd change
  Testscripts/Linux/dpdkSetup.sh
  Testscripts/Linux/dpdkTestPmd.sh
  XML/TestCases/FunctionalTests-DPDK.xml
Labels: PR-Verified, 🐞 Bug

#189 Write the LTP test result into database
  Testscripts/Linux/Linux-Test-Project-Tests.sh
  Testscripts/Windows/Run-LtpSuite.ps1
Labels: enhancement

#175 Update fcopy related cases for Check-FileInLinuxGuest command
  Libraries/CommonFunctions.psm1
  Libraries/IntegrationServiceLibrary.psm1
  Testscripts/Windows/FCOPY-BASIC.ps1
  Testscripts/Windows/FCOPY-DISABLE-ENABLE.ps1
  Testscripts/Windows/FCOPY-FILE-EXISTS.ps1
  Testscripts/Windows/FCOPY-LARGE-FILE.ps1
  Testscripts/Windows/FCOPY-NEGATIVE.ps1
  Testscripts/Windows/FCOPY-NON-ASCII.ps1
  Testscripts/Windows/FCOPY-OVERWRITE.ps1
  Testscripts/Windows/FCOPY-REPEATED-DELETE.ps1
  XML/TestCases/FunctionalTests-FCOPY.xml
Labels: enhancement

#195 Redhat8: various testcases fixes
  Testscripts/Linux/Linux-Test-Project-Tests.sh
  Testscripts/Linux/VERIFY-BOOT-ERROR-WARNINGS.py
  Testscripts/Linux/VERIFY-VHD-PREREQUISITES.py
  Testscripts/Linux/perf_ntttcp.sh
Labels: PR-Verified

#196 Fix find python issues against RHEL8, since it has internal interpreter.
  TestControllers/TestController.psm1
Labels: enhancement

#202 Code coverage: Add test for VMbus driver
  Testscripts/Linux/verify_vmbus_heartbeat_properties.sh
  XML/TestCases/FunctionalTests.xml
Labels: PR-Verified, enhancement

#197 Fix return unknown distro when run against Clear Linux OS.
  Testscripts/Linux/DetectLinuxDistro.sh
Labels: PR-Verified, enhancement

#201 DPDK fixes / improvements
  Testscripts/Linux/dpdkSetup.sh
  Testscripts/Linux/dpdkTestPmd.sh
  Testscripts/Linux/ovs_setup.sh
  Testscripts/Windows/VERIFY-DPDK-OVS.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-DPDK.xml
Labels: PR-Verified, enhancement, 🐞 Bug

#208 Code Coverage: Exclude Test because of VM size
  Utilities/Launch-GcovTest.ps1
Labels: enhancement

#198 Fix for Unsupported gawk on RH6 Distro
  Testscripts/Linux/fio_jason_parser.sh
Labels: 🐞 Bug

#168 Utilities: Added "Tool-Deploy-VM"
  Testscripts/Windows/TOOL-DEPLOYMENT-PROVISION.ps1
  Utilities/Tool-Deploy-VM.ps1
Labels: enhancement

#218 Fix bc tool missing in ORACLE 7.6 when running fio testing.
  Testscripts/Linux/utils.sh
Labels: 🐞 Bug

#209 Fix for unavailable FIO package on 6.x
  Testscripts/Linux/utils.sh
Labels: enhancement

#217 dpdk: added VERIFY-DPDK-NFF-GO TC
  Libraries/TestHelpers.psm1
  Testscripts/Linux/build_test_nff_go.sh
  Testscripts/Windows/VERIFY-DPDK-NFF-GO.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-DPDK.xml
Labels: PR-Verified, enhancement

#211 Azure: Dynamic mapping of Azure VM size to their family
  Libraries/Azure.psm1
Labels: PR-Verified, enhancement

#221 Azure: Enabled cleanup of VMs created using tool-deploy-vm
  Utilities/Remove-OldAzureVMs.ps1
Labels: PR-Verified, enhancement

#204 Switch subscription to Test Only.
  JenkinsPipelines/Run-Boot-Stress-Tests.groovy
  JenkinsPipelines/Run-Linux-Tests.groovy
Labels: enhancement

#220 Modify parameter testconnection for ntttcp testing against nested VM.
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/NestedVmTests.xml
Labels: 🐞 Bug

#219 Correct the count of NVME namespaces
  Testscripts/Linux/nvme_blkdiscard.sh
  Testscripts/Linux/nvme_fstrim.sh
Labels: 🐞 Bug

#229 Utilities: Added support to append multiple subscription usage to html report
  Utilities/Get-SubscriptionUsage.ps1
  Utilities/Get-SubscriptionUsageTopVMs.ps1
Labels: PR-Verified

#232 Remove azure platform for case TIMESYNC-BASIC
  XML/TestCases/FunctionalTests.xml
Labels: Approved

#224 TIMESYNC-NTP: Enable test-case against COREOS
  Testscripts/Linux/TIMESYNC-NTP.sh
  Testscripts/Linux/utils.sh
Labels: 🐞 Bug

#238 Fix : Make sure that LIS version is changed in Install-CustomLIS
  Libraries/CommonFunctions.psm1
Labels: PR-Verified

#234 Fix the bug that Check-FileInLinuxGuest always return true even a file does not exist
  Libraries/CommonFunctions.psm1
  Testscripts/Windows/PRODUCTION-CHECKPOINT.ps1
Labels: PR-Verified

#244 Fix: handled exception which was causing LISAv2 abnormal exit
  TestControllers/TestController.psm1
Labels: 🐞 Bug

#245 Install the Windows Server Backup feature
  Libraries/IntegrationServiceLibrary.psm1
Labels: enhancement

#247 Add test summary into html report.
  Libraries/TestReport.psm1
Labels: enhancement

#250 SR-IOV: Various fixes
  Testscripts/Linux/SR-IOV-Utils.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/SRIOV-CHANGE-RSS.ps1
Labels: PR-Verified, 🐞 Bug

#252 NET-IFUP-IFDOWN: Install packages before running test
  Testscripts/Linux/NET-IFUP-IFDOWN.sh
Labels: enhancement

#249 Fix KDUMP case against RHEL8
  Testscripts/Linux/KDUMP-Config.sh
Labels: PR-Verified, enhancement

#233 Support switch to premium storage automatically
  Libraries/Azure.psm1
  TestControllers/AzureController.psm1
  TestControllers/TestController.psm1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/PerformanceTests.xml
Labels: PR-Verified, enhancement

#248 Fix test case issues for python detect and NESTED-KVM-BASIC-VERIFICATION
  TestControllers/TestController.psm1
  Testscripts/Linux/utils.sh
Labels: enhancement

#256 NVIDIA-GRID-DRIVER: Added support for SLES15
  Testscripts/Linux/gpu-driver-install.sh
  Testscripts/Windows/GPU-DRIVER-INSTALL.ps1
Labels: 🐞 Bug

#241 Force mke2fs to create a filesystem
  Testscripts/Linux/STOR_VHDXResize_GrowFSAfterResize.sh
Labels: enhancement

#255 Penguinator: Add CustomParameters
  JenkinsPipelines/Run-Linux-Tests.groovy
Labels: PR-Verified, enhancement

#261 Enable filesystem case against RHEL 8.
  Libraries/TestHelpers.psm1
  Testscripts/Linux/VERIFY-VHD-PREREQUISITES.py
  Testscripts/Linux/xfstesting.sh
  Testscripts/Windows/FILE-SYSTEM-VERIFICATION-TESTS.ps1
Labels: 🐞 Bug

#254 ETHTOOL-CHECK-STATISTICS supports test for centos
  Testscripts/Linux/Ethtool-Check-Statistics.sh
  Testscripts/Linux/NET-Netperf-Server.sh
Labels: enhancement

#265 Code Coverage: Prepare KVP area by adding tools & daemons install alongside kernel
  Utilities/Launch-GcovTest.ps1
Labels: enhancement

#260 CustomKernel: Azure - wait dpkg lock, use apt-get
  Testscripts/Linux/customKernelInstall.sh
Labels: PR-Verified

#268 Fix issue when run dhclient return error against SLES15.1
  Testscripts/Linux/RELOAD-MODULES.sh
Labels: enhancement

#262 VM-HOT-RESIZE: Refine list of tested VM sizes
  Testscripts/Windows/VM-HOT-RESIZE.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests.xml
Labels: enhancement

#269 NVIDIA-CUDA-DRIVER-VALIDATION: copy the dkms make log
  Testscripts/Linux/gpu-driver-install.sh
  Testscripts/Windows/GPU-DRIVER-INSTALL.ps1
Labels: enhancement

#271 Update the global public ip adress after restarting the VM
  Testscripts/Windows/SETUP-NET-Add-Max-NIC.ps1
Labels: 🐞 Bug

#240 dpdk: added VERIFY-DPDK-VPP TC
  Testscripts/Linux/build_test_vpp.sh
  Testscripts/Linux/customKernelInstall.sh
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/VERIFY-DPDK-VPP.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-DPDK.xml
Labels: PR-Verified, enhancement

#264 Fix issue when vf name changed during ntttcp testing.
  Testscripts/Linux/perf_ntttcp.sh
  Testscripts/Linux/utils.sh
  XML/Other/ReplaceableTestParameters.xml
Labels: enhancement

#267 Refine test summary for DPDK test cases.
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
Labels: PR-Verified, enhancement

#263 Add a default value to parameter RaidOption.
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/NestedVmTests.xml
Labels: 🐞 Bug

#223 Skip DPDK for not matched distro/kernel version.
  Libraries/CommonFunctions.psm1
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
  Testscripts/Windows/VERIFY-DPDK-BUILD-AND-TESTPMD-TEST.ps1
  Testscripts/Windows/VERIFY-DPDK-COMPLIANCE.ps1
  Testscripts/Windows/VERIFY-DPDK-NFF-GO.ps1
  Testscripts/Windows/VERIFY-DPDK-OVS.ps1
  Testscripts/Windows/VERIFY-DPDK-RING-LATENCY.ps1
  Testscripts/Windows/VERIFY-DPDK-VPP.ps1
  Testscripts/Windows/VERIFY-SRIOV-FAILSAFE-FOR-DPDK.ps1
Labels: PR-Verified, enhancement

#280 Modify the path of make.log
  Testscripts/Linux/gpu-driver-install.sh
Labels: 🐞 Bug

#281 dpdk: fix VERIFY-DPDK-FAILSAFE-DURING-TRAFFIC return test
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
  Testscripts/Windows/dpdk-testFailsafe.ps1
Labels: dpdk, 🐞 Bug

#287 PRODUCTION-CHECKPOINT-3CHAIN-VHD: fix compatibility with lisav2 on Hyper-V
  Testscripts/Windows/PRODUCTION-CHECKPOINT-3CHAIN-VHD.ps1
Labels: PR-Verified

#277 IB: Small fixes
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
Labels: PR-Verified, enhancement, rdma, 🐞 Bug

#289 dpdk: add area and tag dpdk-core and dpdk-community
  XML/TestCases/FunctionalTests-DPDK.xml
  XML/TestCases/PerformanceTests-DPDK.xml
Labels: 🆘 Help Wanted
