Repository microsoft/lisa, pull requests merged in 2019-09, with the labels that each got.

#547 GPU CUDA driver test skip in SUSE
  Testscripts/Linux/gpu-driver-install.sh
  Testscripts/Windows/GPU-DRIVER-INSTALL.ps1
Labels: enhancement

#546 CORE-InitrdModulesCheck.sh: Add keyboard module
  Testscripts/Linux/CORE-InitrdModulesCheck.sh
Labels: 🐞 Bug

#548 Fix GPU CUDA|GRID driver test issues in RHEL 8.x
  Testscripts/Linux/gpu-driver-install.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/GPU-DRIVER-INSTALL.ps1
Labels: enhancement

#551 Skipped when coreos unsupport.
  Testscripts/Linux/KDUMP-Config.sh
  Testscripts/Linux/nested_vm_utils.sh
  Testscripts/Linux/xfstesting.sh
Labels: enhancement

#554 Temp fix build error in linux-next.
  Testscripts/Linux/customKernelInstall.sh
Labels: 🐞 Bug

#555 xfstesting.sh: Skip BTRFS cases when check CONFIG_BTRFS_FS is not set in config file
  Testscripts/Linux/xfstesting.sh
Labels: enhancement

#556 Use built-in WALA agent
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
Labels: rdma

#557 Add NetworkManager restart in CreateIfupConfigFile for redhat_8
  Testscripts/Linux/utils.sh
Labels: 🐞 Bug

#562 Fix issues against RHEL8
  Testscripts/Linux/SRIOV-VerifyVF-Connection.sh
Labels: enhancement

#564 Fix TIME-CLOCKSOURCE against linux-next.
  Testscripts/Linux/TIME-CLOCKSOURCE.sh
Labels: PR-Verified, enhancement

#565 Fix test case VERIFY-DISK-WITH-NOBARRIER
  Testscripts/Windows/VERIFY-DISK-WITH-NOBARRIER.ps1
Labels: enhancement

#566 Skip azure file test case when cifs module is not set.
  Testscripts/Linux/xfstesting.sh
Labels: enhancement

#571 Update the virtual switch name for sriov test
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-SRIOV.xml
  XML/TestCases/StressTests.xml
Labels: enhancement

#570 Storage perf: Parse the perf data only when the result is PASS
  Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
  Testscripts/Windows/PERF-STORAGE-OVER-NFS.ps1
Labels: enhancement

#574 Skip SECUREBOOT-VSS test if the VM is not gerneration 2
  Testscripts/Windows/STOR-VSS-BACKUP-RESTORE-PARTITION.ps1
Labels: enhancement

#573 Fix test case STRESSTEST-BOOT-VM-LARGE-MEMORY against setting memory …
  Testscripts/Windows/STRESS-BootLargeMemory.ps1
  Testscripts/Windows/Set-VM-Memory.ps1
Labels: 🐞 Bug

#572 golang-benchmark.sh: Support the golang test on CentOS/Redhat.
  Testscripts/Linux/golang-benchmark.sh
Labels: enhancement

#576 LIS_DEPLOY cases: Modify test result to skipped if kernel version not support
  Testscripts/Windows/LIS-INSTALL-SCENARIOS.ps1
Labels: enhancement

#579 Use stable lagscope version
  Testscripts/Linux/perf_lagscope.sh
  Testscripts/Linux/perf_ntttcp.sh
  Testscripts/Linux/utils.sh
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/NestedVmTests.xml
  XML/TestCases/PerformanceTests.xml
Labels: 🐞 Bug

#580 LIS-Mount-FloppyDisk.ps1: Skip test if kernel does not support floppy
  Testscripts/Windows/LIS-Mount-FloppyDisk.ps1
Labels: enhancement

#569 Enable MVAPICH, Intel and Open MPI in Ubutnu 16.04
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
Labels: PR-Verified, rdma

#568 Fix VMBUS_VERIFY_HEARTBEAT_PROPERTIES
  Testscripts/Linux/verify_vmbus_heartbeat_properties.sh
Labels: 🐞 Bug

#581 Refine the runtime memory test cases
  Libraries/CommonFunctions.psm1
  Testscripts/Windows/DM-HOTADD-STRESS-NG.ps1
  Testscripts/Windows/RUNTIME-MEM-HOTADD.ps1
  Testscripts/Windows/RUNTIME_MEM_HOTADD_CHUNKS.ps1
  Testscripts/Windows/RUNTIME_MEM_MULTIPLEADDREMOVE.ps1
  Testscripts/Windows/RUNTIME_MEM_STRESSHOTREMOVE.ps1
Labels: 🐞 Bug
