Repository microsoft/lisa, pull requests merged in 2019-10, with the labels that each got.

#587 Judge if lock exists before delete resource group (with or without specify UseExistingRG)
  Libraries/Azure.psm1
Labels: enhancement

#588 Fixed the path management of tar command up on the case of internet download
  Testscripts/Linux/SetupRDMA.sh
Labels: Approved, PR-Verified, rdma, 🐞 Bug

#590 Fix PSChecker error.
  TestControllers/ReadyController.psm1
  TestControllers/TestController.psm1
Labels: enhancement

#584 Fix gpu test issue against SLES15.
  Testscripts/Linux/gpu-driver-install.sh
  Utilities/CheckImageUpdate.ps1
Labels: Approved, enhancement

#591 Fix Validate-VHD return multiple value issue.
  Utilities/CheckImageUpdate.ps1
Labels: 🐞 Bug

#592 user the expected VMUser, not global user for DetecLinuxDistro
  Libraries/CommonFunctions.psm1
Labels: enhancement

#594 Support create gen2 VM against customized vhd on Azure platform.
  Libraries/Azure.psm1
  TestControllers/TestController.psm1
Labels: enhancement

#593 Revert "Temp fix build error in linux-next. (#554)"
  Testscripts/Linux/customKernelInstall.sh
Labels: enhancement

#596 Support capture OS image when it is managed type.
  Testscripts/Windows/CAPTURE-VHD-BEFORE-TEST.ps1
Labels: PR-Verified, enhancement

#601 Fix ltp in case data disk is not present
  Testscripts/Linux/Linux-Test-Project-Tests.sh
Labels: enhancement

#603 Fix the parameter HvServer to specify the hvserver when there are more than 1 hvserver
  Testscripts/Windows/NET-IFUP-IFDOWN.ps1
  Testscripts/Windows/RELOAD-MODULES.ps1
Labels: enhancement

#600 Add RestartAllDeployments in Ready Provider + fix some typo
  LISAv2-Framework.psm1
  Libraries/TestLogs.psm1
  TestControllers/TestController.psm1
  TestProviders/ReadyProvider.psm1
  TestProviders/TestProvider.psm1
  Testscripts/Windows/VERIFY-DEPLOYMENT-PROVISION.ps1
Labels: 🐞 Bug

#606 Specify -ssh explicitly when running plink in TestHelper
  Libraries/TestHelpers.psm1
Labels: enhancement

#605 Fix Hyper-V TIME cases for RHEL 8 and AMD host
  Testscripts/Linux/TIME-CLOCKEVENT.sh
  Testscripts/Linux/TIME-CLOCKSOURCE.sh
  Testscripts/Linux/TIMESYNC-NTP.sh
Labels: enhancement

#615 Change test area from NETWORK to SRIOV for ETHTOOL-OFFLOADING test cases
  XML/TestCases/FunctionalTests-Network.xml
Labels: enhancement

#611 Adding Gen2 VM support for SR-IOV tests
  Testscripts/Linux/ETHTOOL-OFFLOADING-SETTING.sh
  Testscripts/Linux/SR-IOV-Utils.sh
  Testscripts/Linux/SRIOV-DisableVF.sh
  Testscripts/Linux/SRIOV-ModuleReload.sh
  Testscripts/Linux/SRIOV-VerifyVF-Connection.sh
Labels: PR-Verified, 🐞 Bug

#618 Remove hardcode eth8 eth_name
  Testscripts/Linux/NET-Max-NICs.sh
Labels: enhancement

#610 Add new test case STRESS-STORAGE-4K-IO-WITHVERIFY
  Testscripts/Linux/perf_fio.sh
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/StressTests.xml
Labels: PR-Verified
