Repository microsoft/lisa, pull requests merged in 2019-08, with the labels that each got.

#491 VERIFY-BOOT-ERROR-WARNINGS： Ignore when syslog or message not present
  Testscripts/Linux/VERIFY-BOOT-ERROR-WARNINGS.py
Labels: enhancement

#494 Merge install_dpdk function to dpdkUtils.sh
  Testscripts/Linux/dpdkSetup.sh
  Testscripts/Linux/dpdkSetupAndRunTest.sh
  Testscripts/Linux/dpdkUtils.sh
  XML/TestCases/FunctionalTests-DPDK.xml
  XML/TestCases/PerformanceTests-DPDK.xml
Labels: dpdk, enhancement

#496 FCOPY-NEGATIVE.ps1: Refine the FCOPY-NEGATIVE test
  Libraries/IntegrationServiceLibrary.psm1
  TestControllers/HyperVController.psm1
  Testscripts/Windows/FCOPY-NEGATIVE.ps1
Labels: 🐞 Bug

#500 NET-TCP-Corruption.ps1: Fix the file hashes not match
  Testscripts/Windows/NET-TCP-Corruption.ps1
Labels: enhancement, 🐞 Bug

#501 SETUP-STOR-TakeRevert-Snapshot.ps1: Add return PASS statement
  Testscripts/Windows/SETUP-STOR-TakeRevert-Snapshot.ps1
Labels: 🐞 Bug

#502 KVP-TestRescind.ps1: Enhance the KVP-TEST-RESCIND test
  TestControllers/HyperVController.psm1
  Testscripts/Windows/KVP-TestRescind.ps1
Labels: enhancement

#504 Catch the exception happened at log collecting and cleanup stage
  TestControllers/TestController.psm1
Labels: PR-Verified

#507 Utilities: Fixed deploy-vm job for CustomVHD
  Utilities/Tool-Deploy-VM.ps1
Labels: PR-Verified, 🐞 Bug

#510 Add dpkg-configure or update-repos in the location of the apt-get update statement
  Testscripts/Linux/KDUMP-Config.sh
  Testscripts/Linux/KDUMP-NFSconfig.sh
  Testscripts/Linux/VERIFY-VHD-PREREQUISITES.py
  Testscripts/Linux/azuremodules.py
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Linux/timesync_config.sh
  Testscripts/Linux/utils.sh
Labels: enhancement

#511 STRESSTEST-RELOAD-LIS-MODULES: fix issue in distro ubuntu16.04
  Testscripts/Windows/RELOAD-MODULES.ps1
Labels: 🐞 Bug

#480 Azure : Added unmanaged VHD cleanup while deleting resource group
  Libraries/Azure.psm1
  TestProviders/AzureProvider.psm1
Labels: Feature-Request, PR-Verified

#509 Skip run Set-CustomConfigInVMs when VM is Windows OS.
  Libraries/CommonFunctions.psm1
  TestProviders/AzureProvider.psm1
  TestProviders/HyperVProvider.psm1
Labels: enhancement, 🐞 Bug

#512 Skip test if the distro is not supported
  Testscripts/Linux/LIS-Check-HypervDaemons-Files-Status.sh
  Testscripts/Windows/LIS-Check-HypervDaemons-Files-Status.ps1
Labels: enhancement

#516 STORAGE-HOT-ADD-DISK-SERIAL/PARALLEL: add unmanaged disks
  Testscripts/Windows/DiskHotAddRemove-Parallel.ps1
  Testscripts/Windows/DiskHotAddRemove-Serial.ps1
Labels: enhancement, 🐞 Bug

#493 Add try catch when current login user doesn't have permission to assign a role.
  Utilities/CreateServicePrincipal.ps1
Labels: enhancement

#506 Refine the storage test cases (Priority=2) on HyperV
  Libraries/CommonFunctions.psm1
  Testscripts/Linux/get_data_disk_dev_name.sh
  Testscripts/Windows/CLEANUP-DiffDiskGrowth.ps1
  Testscripts/Windows/SETUP-DiffDiskGrowth.ps1
  Testscripts/Windows/STOR-ExportImportVM.ps1
  Testscripts/Windows/STOR-VHDX-RESIZE-GROWFS.ps1
  Testscripts/Windows/STOR-VHDX-RESIZE-GROWSHRINK.ps1
  Testscripts/Windows/STORAGE-DiffDiskGrowth.ps1
  Testscripts/Windows/STORAGE-HotRemove.ps1
  Testscripts/Windows/STORAGE-HotRemoveVhdx.ps1
  Testscripts/Windows/STORAGE-HotUnplug.ps1
  XML/TestCases/FunctionalTests-Storage.xml
Labels: PR-Verified, 🐞 Bug

#508 Added dynamic Jenkins menu file creation
  JenkinsPipelines/Scripts/JenkinsTestSelectionMenuGenerator.ps1
Labels: Feature-Request, PR-Verified

#514 DPDK path not found by Lisav2 script fixed
  Testscripts/Linux/dpdkSetupAndRunTest.sh
  Testscripts/Linux/dpdkUtils.sh
Labels: ⚠️ PR-UNDER-TEST

#517 Change Get-AzResourceGroup Tags value when use param "UseExistingRG"
  TestProviders/AzureProvider.psm1
Labels: enhancement

#522 Remove -ExpandProperties for Get-AzResource.
  Libraries/Azure.psm1
Labels: 🐞 Bug

#525 TIMESYNC-NTP: Add a while to wait NTP daemon is running
  Testscripts/Linux/TIMESYNC-NTP.sh
Labels: enhancement, 🐞 Bug

#530 Hyper-V: minor update STOR-ExportImportVM to support run on remote host
  Testscripts/Windows/STOR-ExportImportVM.ps1
Labels: enhancement

#527 Fix issue when server and client VM nic show up not in the same order.
  Testscripts/Linux/SRIOV-VerifyVF-Connection.sh
Labels: 🐞 Bug

#532 Get-Counter dont accept -ComputerName for localhost
  Libraries/HyperV.psm1
Labels: 🐞 Bug
