Repository microsoft/lisa, pull requests merged in 2019-12, with the labels that each got.

#652 Fix issue hit against Debian 9-backports image
  Testscripts/Linux/ETHTOOL-OFFLOADING-SETTING.sh
  Testscripts/Linux/gpu-driver-install.sh
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  XML/TestCases/StressTests.xml
Labels: enhancement

#653 Fix VERIFY-DPDK-PRIMARY-SECONDARY-PROCESSES.
  Testscripts/Linux/dpdk_verify_primary_secondary.sh
  Testscripts/Windows/VERIFY-DPDK-PRIMARY-SECONDARY-PROCESSES.ps1
Labels: dpdk, enhancement

#654 Missing Python binary blocked the test execution
  Testscripts/Linux/verify_vmbus_heartbeat_properties.sh
Labels: PR-Verified, 🐞 Bug

#657 Revert /etc/fstab file after do testing, otherwise it will affect following tests.
  Testscripts/Linux/nobarrier.sh
  Testscripts/Linux/utils.sh
  Testscripts/Linux/xfstesting.sh
Labels: 🐞 Bug

#659 Merged 2 conditions in case statement
  Testscripts/Linux/utils.sh
Labels: PR-Verified

#655 Remove hardcode for /home/${user} and check available execution folder.
  Libraries/CommonFunctions.psm1
  Libraries/TestHelpers.psm1
  Libraries/TestLogs.psm1
  Testscripts/Linux/KVP-BasicChecks.sh
  Testscripts/Windows/NET-IFUP-IFDOWN.ps1
  Testscripts/Windows/VERIFY-DISK-WITH-NOBARRIER.ps1
  Testscripts/Windows/VERIFY-VHD-PREREQUISITES.ps1
Labels: PR-Verified, enhancement

#662 No wait for start VM.
  Libraries/Azure.psm1
  Testscripts/Windows/NET-Add-NIC-After-Provision.ps1
Labels: enhancement, ⚠️ PR-UNDER-TEST

#656 RDMA/IB test script logging improvement
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
Labels: PR-Verified, rdma

#665 Remove targetpw check in SLES.
  Testscripts/Windows/VERIFY-VHD-PREREQUISITES.ps1
Labels: enhancement

#668 SetTestStateSkipped should take exit 0
  Testscripts/Linux/NET-IFUP-IFDOWN.sh
  Testscripts/Linux/STOR_VSS_Set_VSS_Daemon.sh
  Testscripts/Linux/build_install_rdma_core.sh
  Testscripts/Linux/build_test_nff_go.sh
  Testscripts/Linux/build_test_vpp.sh
Labels: 🐞 Bug

#658 Correct the result if no module version is verified
  Testscripts/Linux/VERIFY-LIS-MODULES-VERSION.sh
Labels: PR-Verified, 🐞 Bug

#670 Updated ppa link with Canonical's feedback
  Testscripts/Linux/SetupRDMA.sh
Labels: Approved, PR-Verified, rdma

#671 Update case VERIFY-VHD-PREREQUISITES
  Testscripts/Linux/VERIFY-VHD-PREREQUISITES.py
Labels: enhancement

#661 CentOS 8 - Keep symbol link property when use sed -i command
  Testscripts/Linux/KDUMP-Config.sh
Labels: PR-Verified, enhancement

#666 utils.sh refactoring
  Testscripts/Linux/CORE-ConfigTimeSync.sh
  Testscripts/Linux/ETHTOOL-CHANGE-RINGBUFFER.sh
  Testscripts/Linux/ETHTOOL-CHECK-CHANNEL.sh
  Testscripts/Linux/ETHTOOL-CHECK-FEATURES.sh
  Testscripts/Linux/ETHTOOL-GET-STATISTICS.sh
  Testscripts/Linux/ETHTOOL-GRO-LRO.sh
  Testscripts/Linux/ETHTOOL-HANDLER-HASH-LEVELS.sh
  Testscripts/Linux/ETHTOOL-LINK-KSETTING.sh
  Testscripts/Linux/ETHTOOL-MISC-INFO.sh
  Testscripts/Linux/ETHTOOL-MSG-LEVEL.sh
  Testscripts/Linux/ETHTOOL-OFFLOADING-SETTING.sh
  Testscripts/Linux/ETHTOOL-RSS-HASH-KEY.sh
  Testscripts/Linux/KDUMP-Config.sh
  Testscripts/Linux/NET-Multicast.sh
  Testscripts/Linux/SR-IOV-Utils.sh
  Testscripts/Linux/STOR_VSS_ISCSI_PartitionDisks.sh
  Testscripts/Linux/TIMESYNC-NTP.sh
  Testscripts/Linux/dpdkSetupAndRunTest.sh
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Linux/gpu-driver-install.sh
  Testscripts/Linux/nobarrier.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/SETUP-SR-IOV-Configure.ps1
Labels: Approved, PR-Verified

#674 Fix deadloop in UpdateSummary.
  Testscripts/Linux/utils.sh
Labels: Approved, 🐞 Bug
