Repository microsoft/lisa, pull requests merged in 2019-03, with the labels that each got.

#1 Import module dynamically
  LISAv2-Framework.psm1
  Testscripts/Linux/DetectLinuxDistro.sh
Labels: enhancement

#14 dpdk: fail if negative perf variation is greater than 20%
  Run-LisaV2.ps1
  Testscripts/Linux/dpdkSetup.sh
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
  Testscripts/Windows/dpdk-testFWD.ps1
  Testscripts/Windows/dpdk-testFailsafe.ps1
  Testscripts/Windows/dpdk-testPMD.ps1
Labels: enhancement

#4 Modify TestPlatform in Documents/How-to-use.md
  Documents/How-to-use.md
Labels: enhancement

#11 Fix handling of starting vm after failed setup script
  TestControllers/TestController.psm1
  TestProviders/HyperVProvider.psm1
Labels: bug

#10 Fixed sh scripts exiting with passed when timed out
  Libraries/TestLogs.psm1
Labels: bug

#8 Fixed bug where "ExecutionTag" was not pushed to Telemetry DB
  Libraries/TestLogs.psm1
Labels: PR-Verified, bug

#7 Added "VMGeneration" to Teletemetry DB
  Libraries/Azure.psm1
  Libraries/Database.psm1
  Libraries/HyperV.psm1
  Libraries/TestLogs.psm1
Labels: PR-Verified, enhancement

#21 dpdk: fix dpdk version retrieval
  Testscripts/Linux/dpdk-testFWD.sh
  Testscripts/Linux/dpdk-testFailsafe.sh
  Testscripts/Linux/dpdk-testPMD.sh
  Testscripts/Linux/dpdkUtils.sh
Labels: DO-NOT-MERGE, PR-UNDER-TEST

#16 Use -scp option if default pscp upload/download is failed
  Libraries/TestHelpers.psm1
Labels: enhancement

#18 add .editorconfig to set coding style
  .editorconfig
Labels: enhancement

#15 Enabled Ubuntu 18.04 for Open MPI and MVAPICH MPI
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
Labels: PR-Verified

#24 Fix KDUMP-CRASH-AUTO-SIZE test case.
  Testscripts/Linux/KDUMP-Config.sh
  Testscripts/Windows/KDUMP-TestScript.ps1
Labels: enhancement

#26 SetupRDMA.sh: Fix for wrong function name
  Testscripts/Linux/SetupRDMA.sh
Labels: bug

#23 HyperV: Fixes for FCOPY, KDUMP, PRODUCTION CHECKPOINT
  Libraries/CommonFunctions.psm1
  Libraries/IntegrationServiceLibrary.psm1
  Testscripts/Linux/KDUMP-Execute.sh
  Testscripts/Windows/FCOPY-DISABLE-ENABLE.ps1
  Testscripts/Windows/FCOPY-FILE-EXISTS.ps1
  Testscripts/Windows/FCOPY-LARGE-FILE.ps1
  Testscripts/Windows/FCOPY-OVERWRITE.ps1
  Testscripts/Windows/FCOPY-REPEATED-DELETE.ps1
  Testscripts/Windows/PRODUCTION-CHECKPOINT-3CHAIN-VHD.ps1
  Testscripts/Windows/PRODUCTION-CHECKPOINT.ps1
Labels: PR-Verified, bug

#25 Fix issue 'Test case script result does not match known ones: True True PASS'
  Testscripts/Windows/KDUMP-TestScript.ps1
Labels: enhancement

#29 AzurePlatform: fix typo in availability name and use existing one
  Libraries/Azure.psm1
Labels: bug

#33 Azure : Increase retry count and time for restarting resources
  TestProviders/AzureProvider.psm1
Labels: bug

#32 Output test summary for storage perf test
  Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
Labels: PR-Verified, enhancement

#17 LIS scenarios test : Changed state from FAIL to SKIPPED for kernel update scenarios
  Testscripts/Windows/LIS-INSTALL-SCENARIOS.ps1
Labels: PR-UNDER-TEST, bug

#31 Fix aria2 and sshpass package install issues; add testskipped for BVT-NET-IFUP-IFDOWN and LIS* tests
  Testscripts/Linux/nested_vm_utils.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/BVT-NET-IFUP-IFDOWN.ps1
  Testscripts/Windows/LIS-INSTALL-SCENARIOS.ps1
Labels: PR-Verified, bug, enhancement

#35 SR-IOV: MSI/MSI-X interrupt new TC
  Testscripts/Linux/SR-IOV_Interrupts_Change.sh
  XML/TestCases/FunctionalTests-SRIOV.xml
Labels: enhancement

#5 Fix for LIS-DEPLOY_SCENARIO Testcases
  Libraries/HyperV.psm1
  Testscripts/Windows/LIS-INSTALL-SCENARIOS.ps1
Labels: bug

#37 Added the missing priorty in STRESSTEST-WEB-PARALLEL-ACCESS
  XML/TestCases/StressTests.xml
Labels: bug

#38 Fix test case return unexpected output.
  Testscripts/Windows/DiskHotAddRemove-Parallel.ps1
  Testscripts/Windows/DiskHotAddRemove-Serial.ps1
  Testscripts/Windows/FILE-SYSTEM-VERIFICATION-TESTS.ps1
Labels: enhancement

#36 Add TestArea in test summary.
  Libraries/TestReport.psm1
  TestControllers/TestController.psm1
  Utilities/CheckImageUpdate.ps1
Labels: enhancement

#43 Fix in function Register-RhelSubscription
  Libraries/CommonFunctions.psm1
Labels: bug

#34 Added Long Term Testing deployment and validation scripts
  Testscripts/Linux/prepare_ltpt_vm.sh
  Testscripts/Windows/DEPLOY-LONG-TERM-VM.ps1
  Utilities/LongTerm/Check-Logs.ps1
  Utilities/LongTerm/Get-Values.ps1
  Utilities/LongTerm/check_values.py
  Utilities/LongTerm/parser.ps1
  XML/TestCases/Other.xml
  XML/VMConfigurations/TwoVMs.xml
Labels: PR-Verified, enhancement

#41 Fix nested perf storage test cases issues
  Testscripts/Linux/nested_kvm_storage_perf.sh
  Testscripts/Windows/NESTED-KVM-STORAGE-PERF.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/NestedVmTests.xml
Labels: bug

#45 Fix : HyperV VHD Copy issue
  Libraries/HyperV.psm1
Labels: PR-Verified, bug

#51 Update Linux-Test-Project-Tests.sh
  Testscripts/Linux/Linux-Test-Project-Tests.sh
Labels: enhancement

#49 Azure/Hyperv: Add attempt to change interface settings with ethtool
  Testscripts/Linux/ETHTOOL-LINK-KSETTING.sh
Labels: PR-Verified

#46 Added support to send VM Hardware Platform to Telemetry DB
  Libraries/Database.psm1
  Libraries/TestLogs.psm1
  Testscripts/Linux/CollectLogFile.sh
Labels: PR-Verified, enhancement

#54 Update Sysbench.sh
  Testscripts/Linux/Sysbench.sh
Labels: enhancement

#55 Change ntttcp mode from 1:4 into 1:8
  Testscripts/Linux/perf_ntttcp.sh
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/PerformanceTests.xml
  XML/VMConfigurations/MultiVMs.xml
Labels: enhancement

#59 Add ntttcpVersion for MULTICLIENTS
  XML/TestCases/PerformanceTests.xml
Labels: bug

#39 dpdk: use dpkg sources on native install to rebuild testpmd
  Testscripts/Linux/dpdkSetup.sh
  Testscripts/Linux/dpdkTestPmd.sh
  Testscripts/Linux/dpdk_generic_setup.sh
  Testscripts/Windows/VERIFY-DPDK-OVS.ps1
  XML/TestCases/FunctionalTests-DPDK.xml
Labels: enhancement

#62 dpdk: enable ppa on dpdk perf tests
  Testscripts/Linux/dpdkSetupAndRunTest.sh
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Windows/dpdk-testPMD.ps1
Labels: enhancement

#65 Fix test case STRESSTEST-RELOAD-MODULES-UP issue against Azure.
  Testscripts/Windows/BVT-CORE-RELOAD-MODULES.ps1
Labels: PR-Verified, bug

#66 Fix issue when VM not existed + -UseExistingRG use.
  Libraries/Azure.psm1
Labels: PR-Verified, bug

#68 dpdk: add PERF-DPDK-MULTICORE-PPS-F32 TC for DPDK with 16 cores
  XML/Other/testfwd_pps_lowerbound.xml
  XML/Other/testpmd_pps_lowerbound.xml
  XML/TestCases/PerformanceTests-DPDK.xml
Labels: enhancement
