Repository microsoft/lisa, pull requests merged in 2020-12, with the labels that each got.

#1119 Install meson on CentOS 8
  Testscripts/Linux/dpdkUtils.sh
Labels: dpdk

#1118 DPDK Fix: Netvsc pmd device setup and testpmd options change
  Testscripts/Linux/dpdk-testFWD.sh
  Testscripts/Linux/dpdkPmdsBasicCheck.sh
  Testscripts/Linux/dpdkTestPmd.sh
  Testscripts/Linux/dpdkUtils.sh
Labels: :smiley: Ready-For-Review, dpdk

#1120 Fix regression issue.
  Libraries/TestHelpers.psm1
  TestProviders/HyperVProvider.psm1
Labels: 🐞 Bug

#1091 Fix test issues on SLES15 SP1.
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Linux/nested_vm_utils.sh
Labels: enhancement

#1121 XDP - Wait for VF back.
  Testscripts/Windows/VERIFY-VF-HOT-REMOVE-XDP.ps1
Labels: enhancement

#1125 improve marketplace agreement error message
  lisa/sut_orchestrator/azure/platform_.py
Labels: 🆕 LISAv3

#1112 Fix container related case issues.
  Testscripts/Linux/containers_utils.sh
  Testscripts/Linux/docker_dotnet_app.sh
Labels: 🐞 Bug

#1128 fix regression on timeout
  lisa/util/shell.py
Labels: 🆕 LISAv3

#1130 fix vm cannot be found error
  lisa/sut_orchestrator/azure/platform_.py
Labels: 🆕 LISAv3

#1131 Improve VM query reliability
  lisa/sut_orchestrator/azure/common.py
  lisa/sut_orchestrator/azure/platform_.py
Labels: 🆕 LISAv3

#1133 Update regex to match different formats of host build string in demsg.
  lisa/sut_orchestrator/azure/platform_.py
Labels: 🆕 LISAv3

#1135 Use result.exit_code when run dmesg hit not have enough permission error.
  lisa/tools/dmesg.py
Labels: 🆕 LISAv3

#1134 Fix Kdump and DPDK test case issues.
  Libraries/Azure.psm1
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Linux/nvme_blkdiscard.sh
  XML/TestCases/FunctionalTests.xml
Labels: :smiley: Ready-For-Review, 🐞 Bug

#1140 Fix test case issues on RHEL 8.x
  Testscripts/Linux/VERIFY-VHD-PREREQUISITES.py
  Testscripts/Linux/containers_utils.sh
Labels: :smiley: Ready-For-Review, 🐞 Bug

#1141 Azure: Ignore provisioning timeout exception
  lisa/sut_orchestrator/azure/platform_.py
Labels: 🆕 LISAv3

#1138 DPDK: Change DPDK_SOURCE_URL from 18.11.9 to 20.11
  XML/Other/ReplaceableTestParameters.xml
Labels: dpdk

#1142 Add one more panic pattern.
  lisa/features/serial_console.py
Labels: 🆕 LISAv3
