Repository microsoft/lisa, pull requests merged in 2020-04, with the labels that each got.

#737 Fix KDUMP issue found in ubuntu pipeline.
  Testscripts/Windows/KDUMP-TestScript.ps1
Labels: enhancement

#738 Fix issue when install customlis
  Libraries/CommonFunctions.psm1
Labels: enhancement

#739 Fix issue hit on Ubuntu 20.04
  Testscripts/Linux/CORE-InitrdModulesCheck.sh
  Testscripts/Linux/LSVMBUS.sh
Labels: enhancement

#740 P0 cases - Update size for support both gen1 and gen2 images on Azure.
  XML/AzureVMSizeToHyperVMapping.xml
  XML/TestCases/FunctionalTests-GPU.xml
  XML/TestCases/FunctionalTests-SRIOV.xml
  XML/TestCases/FunctionalTests.xml
  XML/TestCases/NestedVmTests.xml
  XML/VMConfigurations/OneVM.xml
  XML/VMConfigurations/TwoVMs.xml
Labels: enhancement

#741 P1 cases - Update size for support both gen1 and gen2 images on Azure.
  XML/AzureVMSizeToHyperVMapping.xml
  XML/TestCases/FunctionalTests-GPU.xml
  XML/TestCases/FunctionalTests-Network.xml
  XML/TestCases/FunctionalTests-SRIOV.xml
  XML/TestCases/FunctionalTests.xml
  XML/TestCases/PerformanceTests.xml
  XML/VMConfigurations/MultiVMs.xml
  XML/VMConfigurations/OneVM.xml
  XML/VMConfigurations/TwoVMs.xml
Labels: enhancement

#744 P2 and P3 cases - Update size for support both gen1 and gen2 images on Azure.
  XML/TestCases/FunctionalTests-DPDK.xml
  XML/TestCases/NestedVmTests.xml
  XML/TestCases/PerformanceTests.xml
  XML/VMConfigurations/TwoVMs.xml
Labels: enhancement

#742 Fix the SLES repo URL and stop firewall for RHEL 8
  Testscripts/Linux/utils.sh
Labels: 🐞 Bug

#746 Remove permission check/change for sgx device
  Testscripts/Linux/validate-intel-sgx-driver.sh
Labels: enhancement

#745 rename 'enableRoot.sh' and 'enablePasswordLessRoot.sh' and fix potential bugs in existing code
  Libraries/Azure.psm1
  Libraries/CommonFunctions.psm1
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Linux/enable_passwordless_root.sh
  Testscripts/Linux/enable_root.sh
  Testscripts/Linux/nested_hyperv_ntttcp_different_l1_nat.sh
  Testscripts/Linux/nested_hyperv_ntttcp_different_l1_public_bridge.sh
  Testscripts/Linux/nested_kvm_lagscope_different_l1_public_bridge.sh
  Testscripts/Linux/nested_kvm_netperf_pps.sh
  Testscripts/Linux/nested_kvm_netperf_pps_nat.sh
  Testscripts/Linux/nested_kvm_ntttcp_different_l1_nat.sh
  Testscripts/Linux/nested_kvm_ntttcp_different_l1_public_bridge.sh
  Testscripts/Linux/nested_kvm_ntttcp_private_bridge.sh
  Testscripts/Linux/nested_vm_utils.sh
  Testscripts/Windows/SETUP-Inject-IP-Constants.ps1
  Testscripts/Windows/SETUP-SR-IOV-Configure.ps1
  Testscripts/Windows/SRIOV-RUN-COMMON-TEST.ps1
  Utilities/UploadDataToDataBase.ps1
  XML/TestCases/NestedVmTests.xml
Labels: enhancement, 🐞 Bug

#748 Fix HyperV test cases against Ubuntu 20.04 (focal)
  Testscripts/Linux/ETHTOOL-OFFLOADING-SETTING.sh
  Testscripts/Linux/Ethtool-Check-Statistics.sh
  Testscripts/Linux/NET-Test-Network.sh
  Testscripts/Linux/SR-IOV-Utils.sh
  Testscripts/Linux/utils.sh
Labels: enhancement

#750 Try more times when hit dpkg lock during install package on Ubuntu.
  Testscripts/Linux/utils.sh
Labels: enhancement

#751 Fix ibname rename issue.
  Testscripts/Linux/SetupRDMA.sh
Labels: 🐞 Bug

#757 Temporarily switch from clang to gcc for sgx tests
  Testscripts/Linux/validate-intel-sgx-driver.sh
Labels: 🐞 Bug

#747 Add cases STRESSTEST-VERIFY-RESTART-with multiple scenarios.
  Libraries/CommonFunctions.psm1
  TestProviders/AzureProvider.psm1
  Testscripts/Windows/GPU-DRIVER-INSTALL.ps1
  Testscripts/Windows/STRESSTEST-VERIFY-RESTART.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/StressTests.xml
Labels: PR-Verified, enhancement

#756 By default use managed disk.
  Libraries/Azure.psm1
  XML/TestCases/FunctionalTests-Power.xml
  XML/TestCases/FunctionalTests-SGX.xml
  XML/TestCases/FunctionalTests-Storage.xml
  XML/TestCases/FunctionalTests.xml
  XML/TestCases/NestedVmTests.xml
  XML/TestCases/PerformanceTests.xml
  XML/TestCases/StressTests.xml
Labels: enhancement

#758 Restart VM from shell.
  Libraries/CommonFunctions.psm1
  TestProviders/AzureProvider.psm1
Labels: enhancement

#760 Revert "Temporarily switch from clang to gcc for sgx tests (#757)"
  Testscripts/Linux/validate-intel-sgx-driver.sh
Labels: enhancement

#764 Fixed the missing Priority tag in the xml file
  XML/TestCases/FunctionalTests-Power.xml
Labels: 🐞 Bug

#765 update DeleteVMs() logic, add support for NetworkSecurityGroupRules, refine logic for testing with TiP
  LISAv2-Framework.psm1
  Libraries/Azure.psm1
  TestControllers/AzureController.psm1
  TestControllers/TestController.psm1
  TestProviders/AzureProvider.psm1
  Testscripts/Windows/NET-Add-NIC-After-Provision.ps1
  XML/Other/NetworkSecurityGroupRules.xml
Labels: Infra-change, enhancement
