Repository microsoft/lisa, pull requests merged in 2020-10, with the labels that each got.

#1037 Fixed the new problems in kernel compilation in redhat distro
  Testscripts/Linux/SetupHbKernel.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/CPU-Offline.ps1
  Testscripts/Windows/HB-CLOCKSYNC.ps1
  Testscripts/Windows/Power-Hibernate.ps1
  Testscripts/Windows/VMRESIZE-HB.ps1
  Testscripts/Windows/WORKLOAD-HB.ps1
Labels: :smiley: Ready-For-Review, Verified_Redhat

#1040 Updated IB tests with ND support scenario.
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified

#1038 VERIFY-XDP-VF-HOT-REMOVE: Verify XDP with VF hot removal and readd
  Testscripts/Linux/XDPUtils.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/VERIFY-VF-HOT-REMOVE-XDP.ps1
  XML/TestCases/FunctionalTests-XDP.xml
Labels: :smiley: Ready-For-Review, enhancement

#1043 Fix typo.
  Testscripts/Linux/TIME-CLOCKSOURCE.sh
Labels: 🐞 Bug

#1046 Update CORE-VerifyHeartBeat.ps1 with more sleep before getting vm hea…
  Testscripts/Windows/CORE-VerifyHeartBeat.ps1
Labels: :thumbsup: PR-Verified

#1045 PERF-XDP-FORWARD-COMPARISON: New test-case to compare XDP performance
  Testscripts/Linux/XDPForwardingTest.sh
  Testscripts/Windows/PERF-XDP-TX-FORWARD.ps1
  XML/TestCases/PerformanceTests.xml
Labels: :smiley: Ready-For-Review, enhancement

#1049 DPDK-FWD-PPS: Fix parameter order
  Testscripts/Linux/dpdk-testFWD.sh
Labels: :smiley: Ready-For-Review, dpdk

#1048 Add a new RAID0 disk test
  Testscripts/Linux/perf_fio.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
  XML/TestCases/PerformanceTests.xml
  XML/VMConfigurations/OneVM.xml
Labels: :smiley: Ready-For-Review, Verified_Canonical, Verified_Redhat

#1051 Check only VF tx counter and replace with new default sku
  Testscripts/Windows/Power-Hibernate.ps1
  XML/TestCases/FunctionalTests-Power.xml
Labels: :smiley: Ready-For-Review, Verified_Canonical, Verified_Redhat

#1052 Update FunctionalTests-InfiniBand.xml
  Testscripts/Linux/TestRDMA_MultiVM.sh
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
Labels: Verified_Redhat, ⚠️ PR-UNDER-TEST

#1056 Update OpenMPI to 4.0.5
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  XML/Other/ReplaceableTestParameters.xml
Labels: :smiley: Ready-For-Review, Verified_Canonical, Verified_Redhat, Verified_SUSE

#1062 DPDK Fix: Remove mlx pmd config for meson build system
  Testscripts/Linux/dpdkUtils.sh
Labels: :smiley: Ready-For-Review, dpdk

#1053 remove unittest.TestCase
  examples/testsuites/helloworld.py
  examples/testsuites/multinodes.py
  examples/testsuites/withscript.py
  lisa/testsuite.py
  poetry.lock
  pyproject.toml
Labels: 🆕 LISAv3

#1059 remove 1 core vm sizes from default
  lisa/sut_orchestrator/azure/platform_.py
  lisa/sut_orchestrator/azure/tests/azure_locations.json
  lisa/sut_orchestrator/azure/tests/test_prepare.py
Labels: 🆕 LISAv3

#1068 Add support for one string arm image
  lisa/sut_orchestrator/azure/platform_.py
Labels: 🆕 LISAv3
