Repository microsoft/lisa, pull requests merged in 2020-03, with the labels that each got.

#719 Load modules for SLES 15 SP1.
  Testscripts/Linux/dpdkUtils.sh
Labels: 🐞 Bug

#722 Added softlink python if not exists
  Testscripts/Linux/SetupRDMA.sh
Labels: PR-Verified, rdma

#724 SGX - Delete state.txt file before testing.
  Testscripts/Linux/validate-intel-sgx-driver.sh
  XML/TestCases/FunctionalTests-SGX.xml
Labels: 🐞 Bug

#727 Fix issue when install rdma core on Ubuntu
  Testscripts/Linux/build_install_rdma_core.sh
  Testscripts/Linux/dpdk_verify_primary_secondary.sh
Labels: 🐞 Bug

#735 Improve the log in KDUMP-TestScript
  Testscripts/Windows/KDUMP-TestScript.ps1
Labels: PR-Verified

#733 Fix collect_VM_properties
  Testscripts/Linux/utils.sh
Labels: 🐞 Bug
