Repository microsoft/lisa, pull requests merged in 2020-09, with the labels that each got.

#999 Enable security profiles in ARM template
  Libraries/Azure.psm1
  Libraries/CommonFunctions.psm1
  README.md
  TestControllers/AzureController.psm1
  XML/TestCases/FunctionalTests-SGX.xml
  XML/TestCases/FunctionalTests-TVM.xml
Labels: :smiley: Ready-For-Review

#1000 Add Check_lsvmbus in utils.sh and gpu-driver-install.sh
  Testscripts/Linux/LSVMBUS.sh
  Testscripts/Linux/gpu-driver-install.sh
  Testscripts/Linux/utils.sh
  Testscripts/Linux/verify_vmbus_heartbeat_properties.sh
Labels: :smiley: Ready-For-Review

#995 PERF-XDP-TX-FORWARD-MULTICORE/SINGLECORE: New testcases to check XDP Forwarding performance.
  Testscripts/Linux/XDPDumpSetup.sh
  Testscripts/Linux/XDPForwardingTest.sh
  Testscripts/Linux/XDPUtils.sh
  Testscripts/Linux/pktgenSetup.sh
  Testscripts/Windows/PERF-XDP-RX-DROP.ps1
  Testscripts/Windows/PERF-XDP-TX-FORWARD.ps1
  XML/TestCases/PerformanceTests.xml
Labels: :smiley: Ready-For-Review, enhancement

#1005 Update getting started instructions
  CONTRIBUTING.md
  README.md
Labels: 🆕 LISAv3

#1011 Get key file from internal repo.
  Libraries/TestHelpers.psm1
Labels: enhancement

#1012 Get sbinfo from packages.mircosoft.com at runtime
  .gitignore
  Libraries/TestHelpers.psm1
  Testscripts/Linux/TVM-TestSecureBootCompatibility.sh
  XML/TestCases/FunctionalTests-TVM.xml
Labels: enhancement

#1017 Added new common function, is_hpc_vm
  Testscripts/Linux/LSVMBUS.sh
  Testscripts/Linux/gpu-driver-install.sh
  Testscripts/Linux/utils.sh
  Testscripts/Linux/verify_vmbus_heartbeat_properties.sh
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified, rdma

#997 Bring up Mariadb test into LISAv2
  Testscripts/Linux/perf_mariadb.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/PERF-TWOVM-MIDDLEWARE-BENCHMARK.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/PerformanceTests.xml
  XML/VMConfigurations/TwoVMs.xml
Labels: :smiley: Ready-For-Review

#1018 Added a new test for HPC VM inside.
  Testscripts/Linux/check_IB_SRIOV.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/VERIFY-HPC-VM.ps1
  XML/TestCases/FunctionalTests-KernelDebug.xml
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified, rdma

#1019 Add unittest for lisarunner, and bug fixes
  lisa/action.py
  lisa/commands.py
  lisa/environment.py
  lisa/platform_.py
  lisa/schema.py
  lisa/test_runner/lisarunner.py
  lisa/test_runner/tests/__init__.py
  lisa/test_runner/tests/test_lisarunner.py
  lisa/tests/test_env_requirement.py
  lisa/tests/test_environment.py
  lisa/tests/test_platform.py
  lisa/tests/test_testselector.py
  lisa/tests/test_testsuite.py
  lisa/testsuite.py
  lisa/util/logger.py
  lisa/util/process.py
Labels: 🆕 LISAv3

#1021 Fixed the Clock Source information in different CentOS/RHEL versions
  Testscripts/Linux/TIME-CLOCKSOURCE.sh
Labels: Verified_Canonical, Verified_Redhat, Verified_SUSE, 🐞 Bug

#1020 Implement to deploy multiple nics
  examples/testsuites/helloworld.py
  examples/testsuites/multinodes.py
  lisa/schema.py
  lisa/sut_orchestrator/azure/arm_template.json
  lisa/sut_orchestrator/azure/azure.py
  lisa/util/__init__.py
  lisa/util/shell.py
Labels: 🆕 LISAv3

#1010 DPDK: Installation Fix for RHEL, SUSE, CentOS
  Testscripts/Linux/dpdk-testFWD.sh
  Testscripts/Linux/dpdk-testFailsafe.sh
  Testscripts/Linux/dpdk-testPMD.sh
  Testscripts/Linux/dpdkTestPmd.sh
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
  Testscripts/Windows/VERIFY-DPDK-BUILD-AND-TESTPMD-TEST.ps1
Labels: :smiley: Ready-For-Review, dpdk

#1025 Azure FILE-SYSTEM-VERIFICATION-TESTS has SMB3.0 supporting distro list
  Testscripts/Linux/xfstesting.sh
  Testscripts/Windows/FILE-SYSTEM-VERIFICATION-TESTS.ps1
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified

#1029 Just added the user friendly logging in TIME-CLOCKSOURCE
  Testscripts/Linux/TIME-CLOCKSOURCE.sh
Labels: :thumbsup: PR-Verified

#1030 Update L3Cache-Verify.sh for unsupported case
  Testscripts/Linux/L3Cache-Verify.sh
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified

#1031 vmbus interrupt check test is no longer valid in big size Azure VM
  Testscripts/Linux/verify_vmbus_interrupts.sh
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified

#1032 TIME_CLOCKSOURCE now accepts both types - hyperv_clocksource and hv_clocksource
  Testscripts/Linux/TIME-CLOCKSOURCE.sh
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified
