Repository microsoft/lisa, pull requests merged in 2020-11, with the labels that each got.

#1079 Add fix for one string arm image
  lisa/sut_orchestrator/azure/platform_.py
Labels: 🆕 LISAv3

#1080 Update kernel version, insert image, platform, vmsize info into testresultmessage
  examples/testsuites/helloworld.py
  lisa/platform_.py
  lisa/sut_orchestrator/azure/platform_.py
  lisa/testsuite.py
  lisa/tools/uname.py
Labels: 🆕 LISAv3

#1074 support storage account in arm template
  lisa/sut_orchestrator/azure/arm_template.json
  lisa/sut_orchestrator/azure/platform_.py
Labels: 🆕 LISAv3

#1083 Support to accept terms for gallery images
  lisa/sut_orchestrator/azure/arm_template.json
  lisa/sut_orchestrator/azure/common.py
  lisa/sut_orchestrator/azure/cred_wrapper.py
  lisa/sut_orchestrator/azure/platform_.py
  poetry.lock
  pyproject.toml
Labels: 🆕 LISAv3

#1087 Collect WALA Version.
  lisa/sut_orchestrator/azure/platform_.py
  lisa/sut_orchestrator/azure/tools.py
Labels: 🆕 LISAv3

#1088 Fix LIS version collection pattern.
  lisa/tools/modinfo.py
Labels: 🆕 LISAv3

#1084 attach deployment failure to test case
  lisa/runner.py
Labels: 🆕 LISAv3

#1090 Collect image, size, location and platform info when deploy failed.
  lisa/node.py
  lisa/platform_.py
  lisa/runner.py
  lisa/sut_orchestrator/azure/platform_.py
  lisa/testsuite.py
Labels: 🆕 LISAv3

#1092 Removed GPL license
  Testscripts/Linux/perf_fio.sh
  Testscripts/Linux/perf_fio_nfs.sh
  Testscripts/Linux/restart-interface-reload-netvsc.sh
Labels: :smiley: Ready-For-Review

#1093 Update operating system id for SUSE
  lisa/operating_system.py
Labels: 🆕 LISAv3

#1094 Update pattern for checking panic and call trace from dmesg.
  lisa/tools/dmesg.py
  testsuites/basic/provisioning.py
Labels: 🆕 LISAv3

#1097 fix encoding errors of log output
  lisa/util/logger.py
Labels: 🆕 LISAv3

#1101 Add ignore message list for kernel panic.
  lisa/features/serial_console.py
  testsuites/basic/provisioning.py
Labels: 🆕 LISAv3

#1102 Not reset node.is_connected and collect VM generation info
  lisa/node.py
Labels: 🆕 LISAv3

#1103 Support bool/string format for reserve_environment
  .github/workflows/continuous-integration-workflow.yml
  lisa/schema.py
  lisa/sut_orchestrator/azure/platform_.py
  lisa/tests/test_platform.py
Labels: 🆕 LISAv3

#1108 dpdk-testFWD: Updates testcase with respect to change in DPDK code.
  Testscripts/Linux/dpdk-testFWD.sh
  Testscripts/Linux/dpdkUtils.sh
Labels: :smiley: Ready-For-Review, dpdk

#1111 Fix XDP test case issues.
  Testscripts/Linux/perf_ntttcp.sh
  Testscripts/Windows/PERF-XDP-NTTTCP.ps1
  Testscripts/Windows/PERF-XDP-TCP-LATENCY.ps1
  Testscripts/Windows/VERIFY-VF-HOT-REMOVE-XDP.ps1
Labels: 🐞 Bug

#1114 Fix DPDK filter log for fail safe.
  Testscripts/Linux/build_test_vpp.sh
  Testscripts/Linux/dpdk-testFailsafe.sh
  Testscripts/Windows/VERIFY-SRIOV-FAILSAFE-FOR-DPDK.ps1
Labels: ⚠️ PR-UNDER-TEST
