Repository microsoft/lisa, pull requests merged in 2020-06, with the labels that each got.

#837 vmbus channel reassignment and cpu offline test improvement
  Testscripts/Linux/channel_change.sh
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified

#838 XDP Testcases: Introduced XDPDump_Repo_URL replaceable string
  Testscripts/Linux/XDPDumpSetup.sh
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-XDP.xml
Labels: :smiley: Ready-For-Review

#841 Testscripts/Linux/channel_change: Remove two test scenarios
  Testscripts/Linux/channel_change.sh
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified

#833 VERIFY-XDP-ACTION-DROP & VERIFY-XDP-ACTION-TX
  Testscripts/Linux/XDP-Action.sh
  Testscripts/Windows/VERIFY-XDP-ACTION.ps1
  XML/TestCases/FunctionalTests-XDP.xml
Labels: :smiley: Ready-For-Review, enhancement

#846 Ignore error message in VERIFY-BOOT-ERROR-WARNINGS case
  XML/Other/ignorable-boot-errors.xml
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified

#843 Update gpu-driver-install.sh
  Testscripts/Linux/Linux-Kernel-Self-Tests.sh
  Testscripts/Linux/gpu-driver-install.sh
  Testscripts/Linux/utils.sh
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified

#849 Support downstream kernel in Power-hibernate and fix issues
  Testscripts/Linux/SetupHbKernel.sh
  Testscripts/Windows/Power-Hibernate.ps1
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified

#850 VERIFY-XDP-MTU: New Testcase to verify various MTU Sizes
  Testscripts/Linux/XDP-MTUVerify.sh
  Testscripts/Windows/VERIFY-XDP-MTU.ps1
  XML/TestCases/FunctionalTests-XDP.xml
Labels: :smiley: Ready-For-Review

#853 Update Hibernate test case
  Testscripts/Linux/SetupHbKernel.sh
  Testscripts/Windows/Power-Hibernate.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-Power.xml
Labels: :smiley: Ready-For-Review

#851 Add new case Power-hibernate-SRIOV for BZ#1841973
  Testscripts/Windows/Power-Hibernate.ps1
  XML/TestCases/FunctionalTests-Power.xml
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified

#856 VERIFY-XDP-ACTION-ABORTED: New testcase to validate XDP ACTION ABORTED
  Testscripts/Linux/XDP-Action.sh
  XML/TestCases/FunctionalTests-XDP.xml
Labels: :smiley: Ready-For-Review, enhancement

#857 Install distro module if not exists in WALA-VERIFY-VERBOSE-ENABLED-LOGS case
  Testscripts/Linux/WALA-VERIFY-VERBOSE-ENABLED-LOGS.py
Labels: enhancement

#852 Update for ssh key authentication
  LISAv2-Framework.psm1
  Libraries/Azure.psm1
  Libraries/CommonFunctions.psm1
  Libraries/TestHelpers.psm1
  README.md
  Run-LisaV2.ps1
  TestControllers/AzureController.psm1
  TestControllers/TestController.psm1
  TestProviders/AzureProvider.psm1
  Testscripts/Linux/enable_passwordless_root.sh
  Testscripts/Linux/enable_root.sh
  Testscripts/Linux/nested_kvm_lagscope_different_l1_public_bridge.sh
  Testscripts/Linux/nested_kvm_netperf_pps.sh
  Testscripts/Linux/nested_kvm_netperf_pps_nat.sh
  Testscripts/Linux/nested_kvm_ntttcp_different_l1_nat.sh
  Testscripts/Linux/nested_kvm_ntttcp_different_l1_public_bridge.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/NESTED-KVM-LAGSCOPE-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-NETPERF-PPS.ps1
  Testscripts/Windows/NESTED-KVM-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/RELOAD-MODULES.ps1
  Utilities/Tool-Deploy-VM.ps1
  Utilities/UpdateGlobalConfigurationFromXmlSecrets.ps1
  XML/GlobalConfigurations.xml
  XML/TestParameters.xml
Labels: enhancement, ⚠️ PR-UNDER-TEST

#858 New test Hibernate with network workload in the same script with storage workload test
  Documents/How-to-use.md
  Testscripts/Linux/SetupHbKernel.sh
  Testscripts/Windows/Power-Hibernate.ps1
  Testscripts/Windows/STORAGE-FIO-HB.ps1
  Testscripts/Windows/WORKLOAD-HB.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-Power.xml
  XML/VMConfigurations/OneVM.xml
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified

#865 Checked queue size and interrupt counts
  Testscripts/Windows/Power-Hibernate.ps1
  Testscripts/Windows/WORKLOAD-HB.ps1
  XML/TestCases/FunctionalTests-Power.xml
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified

#863 Fix test issue hit in SLES15 SP1.
  Testscripts/Linux/gpu-driver-install.sh
  Testscripts/Linux/utils.sh
Labels: enhancement

#874 Add a utils function to identify platform and enhance ETHTOOL-GRO-LRO
  Testscripts/Linux/ETHTOOL-GRO-LRO.sh
  Testscripts/Linux/utils.sh
Labels: enhancement

#845 add Xilinx fpga validation test
  Libraries/TestLogs.psm1
  Testscripts/Linux/fpga-card-validation.sh
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-FPGA.xml
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified

#879 Fix break.
  Libraries/TestLogs.psm1
Labels: 🐞 Bug

#873 Add new test case, Hibernate VM size change
  Testscripts/Windows/VMRESIZE-HB.ps1
  XML/TestCases/FunctionalTests-Power.xml
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified

#864 Long hibernation stress test
  Testscripts/Linux/SetupHbKernel.sh
  Testscripts/Windows/Power-Hibernate.ps1
  Testscripts/Windows/WORKLOAD-HB.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/StressTests.xml
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified

#878 Added new memory workload in hibernation test
  Testscripts/Windows/WORKLOAD-HB.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-Power.xml
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified

#875 [VERIFY-VHD-PREREQUISITES]Read /boot/grub2/grubenv when version >= 8.0
  Testscripts/Linux/VERIFY-VHD-PREREQUISITES.py
Labels: enhancement

#880 Update FunctionalTests-Power.xml
  XML/TestCases/FunctionalTests-Power.xml
  XML/TestCases/FunctionalTests-SGX.xml
  XML/TestCases/PerformanceTests.xml
  XML/TestCases/StressTests.xml
Labels: :ok_hand: Approved, :smiley: Ready-For-Review

#877 VERIFY-XDP-COMPLANCE supports RHEL-8
  Testscripts/Linux/XDPDumpSetup.sh
  Testscripts/Windows/VERIFY-XDP-COMPLIANCE.ps1
Labels: :thumbsup: PR-Verified

#882 Fixing code integration gap in hibernation tests
  Testscripts/Windows/HB-CLOCKSYNC.ps1
  Testscripts/Windows/Power-Hibernate.ps1
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified, 🐞 Bug

#884 Fix small issue in SetupHbKernel.sh
  Testscripts/Linux/SetupHbKernel.sh
Labels: 🐞 Bug

#885 Support RHEL-8 in all the XDP cases
  Testscripts/Linux/XDP-Action.sh
  Testscripts/Windows/VERIFY-SRIOV-FAILSAFE-XDP.ps1
  Testscripts/Windows/VERIFY-XDP-ACTION.ps1
  Testscripts/Windows/VERIFY-XDP-LOAD-UNLOAD.ps1
  Testscripts/Windows/VERIFY-XDP-MTU.ps1
  Testscripts/Windows/VERIFY-XDP-MULTIPLE-NICS.ps1
Labels: enhancement

#886 Fix hung during run apt upgrade
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/validate-intel-sgx-driver.sh
  XML/TestCases/FunctionalTests-SGX.xml
Labels: enhancement, 🐞 Bug
