Repository microsoft/lisa, pull requests merged in 2020-08, with the labels that each got.

#944 Fix issue the vhd name is null in CAPTURE-VHD-BEFORE-TEST test case
  Testscripts/Windows/CAPTURE-VHD-BEFORE-TEST.ps1
Labels: :smiley: Ready-For-Review

#897 PERF-XDP-TCP-LATENCY: New testcase to verify XDP Latency performance
  Testscripts/Linux/perf_lagscope.sh
  Testscripts/Windows/PERF-NETWORK-TCP-LATENCY-LAGSCOPE.ps1
  Testscripts/Windows/PERF-XDP-TCP-LATENCY.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/PerformanceTests.xml
Labels: :smiley: Ready-For-Review, enhancement

#954 Add badges and restrict workflows to PRs
  .github/workflows/continuous-integration-workflow.yml
  README.md
Labels: 🆕 LISAv3

#929 DPDK: Extend netvsc pmd support
  Testscripts/Linux/dpdk-testFWD.sh
  Testscripts/Linux/dpdk-testFailsafe.sh
  Testscripts/Linux/dpdk-testPMD.sh
  Testscripts/Linux/dpdkTestPmd.sh
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Linux/utils.sh
  XML/TestCases/FunctionalTests-DPDK.xml
  XML/TestCases/PerformanceTests-DPDK.xml
Labels: :smiley: Ready-For-Review, dpdk, enhancement

#948 Remove resource disk on HyperV and update storage test cases.
  Libraries/HyperV.psm1
  Testscripts/Linux/PartitionDisks.sh
  Testscripts/Linux/PartitionMultipleDisks.sh
  Testscripts/Linux/STOR-Large-CopyFile.sh
  Testscripts/Linux/STOR-Lis-Disk.sh
  Testscripts/Linux/STORAGE-HotRemove.sh
  Testscripts/Linux/STORAGE-LargeDisk.sh
  Testscripts/Linux/STOR_VSS_Disk_Fail.sh
  Testscripts/Linux/STOR_VSS_Disk_Mount_Multi_Paths.sh
  Testscripts/Linux/STOR_VSS_ISCSI_PartitionDisks.sh
  Testscripts/Linux/get_data_disk_dev_name.sh
  Testscripts/Linux/nested_kvm_storage_perf.sh
  Testscripts/Linux/nobarrier.sh
  Testscripts/Linux/perf_fio.sh
  Testscripts/Linux/pktgenSetup.sh
  Testscripts/Linux/utils.sh
  Testscripts/Linux/validate-da.sh
  Testscripts/Windows/CLEANUP-DiffDiskGrowth.ps1
  Testscripts/Windows/STORAGE-HotUnplug.ps1
  Testscripts/Windows/VERIFY-SRIOV-FAILSAFE-XDP.ps1
  XML/TestCases/Other.xml
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified

#959 implement tool installation
  examples/testsuites/helloworld.py
  examples/testsuites/withscript.py
  lisa/core/decorator/caseMetadata.py
  lisa/core/decorator/suiteMetadata.py
  lisa/core/environment.py
  lisa/core/executable.py
  lisa/core/node.py
  lisa/core/nodeFactory.py
  lisa/core/sshConnection.py
  lisa/core/testSuite.py
  lisa/core/tool.py
  lisa/executable/__init__.py
  lisa/executable/echo.py
  lisa/executable/ping.py
  lisa/main.py
  lisa/test_runner/lisarunner.py
  lisa/tool/__init__.py
  lisa/tool/echo.py
  lisa/tool/git.py
  lisa/tool/ntttcp.py
  lisa/tool/uname.py
  lisa/util/constants.py
  lisa/util/env.py
  lisa/util/executableResult.py
  lisa/util/logger.py
  lisa/util/process.py
  lisa/util/shell.py
  poetry.lock
  pyproject.toml
Labels: 🆕 LISAv3

#962 Fix types and add type checking to CI
  .github/workflows/continuous-integration-workflow.yml
  lisa/core/decorator/suiteMetadata.py
  lisa/core/environment.py
  lisa/core/node.py
  lisa/core/nodeFactory.py
  lisa/core/platformFactory.py
  lisa/core/testSuite.py
  lisa/core/tool.py
  lisa/tool/git.py
  lisa/tool/ntttcp.py
  lisa/tool/uname.py
  lisa/util/process.py
  lisa/util/shell.py
Labels: 🆕 LISAv3

#960 Fix case DYNAMIC-MEMORY-VERIFY-UDEV and MOUNT-CD
  Testscripts/Linux/CORE-InitrdModulesCheck.sh
  Testscripts/Linux/DM_HotAdd_Verify_udev.sh
  Testscripts/Linux/ETHTOOL-GRO-LRO.sh
  Testscripts/Linux/KDUMP-Config.sh
  Testscripts/Linux/LIS-Mount-CD.sh
  Testscripts/Linux/NET-IFUP-IFDOWN.sh
  Testscripts/Linux/NET-Max-NICs.sh
  Testscripts/Linux/NET-Test-Legacy.sh
  Testscripts/Linux/RELOAD-MODULES.sh
  Testscripts/Linux/VERIFY-LIS-MODULES-VERSION.sh
  Testscripts/Linux/restart-interface-reload-netvsc.sh
  Testscripts/Linux/utils.sh
  Testscripts/Linux/xfstesting.sh
Labels: :thumbsup: PR-Verified, enhancement

#966 Ehance apache test case and fix database table fields
  Testscripts/Linux/perf_apache.sh
  Testscripts/Windows/PERF-TWOVM-MIDDLEWARE-BENCHMARK.ps1
Labels: :smiley: Ready-For-Review

#968 Add new fields for the table of TCP latency
  Testscripts/Linux/perf_lagscope.sh
  Testscripts/Windows/PERF-NETWORK-TCP-LATENCY-LAGSCOPE.ps1
Labels: :smiley: Ready-For-Review

#969 Add ShellCheck to CI
  .github/workflows/continuous-integration-workflow.yml
Labels: 🆕 LISAv3

#965 Implement custom script
  .github/workflows/continuous-integration-workflow.yml
  README.md
  examples/runbook/hello_world_remote.yml
  examples/testsuites/helloworld.py
  examples/testsuites/scripts/echo.sh
  examples/testsuites/withscript.py
  lisa/__init__.py
  lisa/commands.py
  lisa/core/__init__.py
  lisa/core/action.py
  lisa/core/customScript.py
  lisa/core/decorator/testCaseMetadata.py
  lisa/core/decorator/testSuiteMetadata.py
  lisa/core/environment.py
  lisa/core/environmentFactory.py
  lisa/core/node.py
  lisa/core/nodeFactory.py
  lisa/core/platform.py
  lisa/core/platformFactory.py
  lisa/core/testFactory.py
  lisa/core/testSuite.py
  lisa/core/tool.py
  lisa/main.py
  lisa/parameter_parser/argparser.py
  lisa/parameter_parser/config.py
  lisa/sut_orchestrator/ready.py
  lisa/test_runner/lisarunner.py
  lisa/tool/echo.py
  lisa/tool/git.py
  lisa/tool/ntttcp.py
  lisa/tool/uname.py
  lisa/util/connectionInfo.py
  lisa/util/constants.py
  lisa/util/env.py
  lisa/util/exceptions.py
  lisa/util/executableResult.py
  lisa/util/logger.py
  lisa/util/process.py
  lisa/util/shell.py
Labels: 🆕 LISAv3

#971 Convert the type before inserting database
  Testscripts/Windows/PERF-TWOVM-MIDDLEWARE-BENCHMARK.ps1
Labels: :smiley: Ready-For-Review

#961 DPDK: Change installation steps as make is deprecated
  Testscripts/Linux/dpdkTestPmd.sh
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Linux/dpdk_verify_primary_secondary.sh
Labels: :smiley: Ready-For-Review, dpdk, enhancement

#975 Add optional LTP installation path
  Testscripts/Linux/Linux-Test-Project-Tests.sh
  Testscripts/Windows/Run-LtpSuite.ps1
Labels: enhancement

#958 Fix issues to support downstream kernel in POWER-HIBERNATE
  Testscripts/Linux/SetupHbKernel.sh
Labels: Verified_Canonical, Verified_Redhat, Verified_SUSE

#974 Write initial Contributing Guidelines draft
  .github/workflows/continuous-integration-workflow.yml
  CONTRIBUTING.md
Labels: 🆕 LISAv3

#979 VERIFY-DPDK-RING-LATENCY: Updated testcase with meson build steps
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Linux/run_dpdk_ring_latency.sh
Labels: :smiley: Ready-For-Review

#981 Fix VERIFY-DPDK-NFF-GO
  Testscripts/Linux/build_test_nff_go.sh
  XML/TestCases/FunctionalTests-DPDK.xml
Labels: 🐞 Bug

#982 Add ignore warning message of WALA
  XML/Other/ignorable-boot-errors.xml
Labels: :smiley: Ready-For-Review, enhancement

#973 Bring up scheduler benchmark test from lis-test
  Testscripts/Linux/perf_scheduler.sh
  Testscripts/Windows/PERF-SCHEDULER.ps1
  Testscripts/Windows/PERF-TWOVM-MIDDLEWARE-BENCHMARK.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/PerformanceTests.xml
Labels: :smiley: Ready-For-Review

#990 Add check for irqbalance.
  Testscripts/Linux/VERIFY-LINUX-CONFIGURATION.py
Labels: enhancement

#994 DPDK_SOURCE_URL: Updated with 18.11.9 to support latest kernel changes.
  XML/Other/ReplaceableTestParameters.xml
Labels: :smiley: Ready-For-Review, dpdk

#987 Fix XDP cases.
  Testscripts/Linux/XDP-Action.sh
  Testscripts/Linux/XDP-MTUVerify.sh
  Testscripts/Linux/XDPDumpSetup.sh
  Testscripts/Linux/dpdkPmdsBasicCheck.sh
  Testscripts/Linux/pktgenSetup.sh
  Testscripts/Windows/DPDK-PMDS-BASIC-CHECK.ps1
  Testscripts/Windows/PERF-XDP-RX-DROP.ps1
  Testscripts/Windows/PERF-XDP-TCP-LATENCY.ps1
  Testscripts/Windows/VERIFY-SRIOV-FAILSAFE-XDP.ps1
  Testscripts/Windows/VERIFY-XDP-ACTION.ps1
  Testscripts/Windows/VERIFY-XDP-COMPLIANCE.ps1
  Testscripts/Windows/VERIFY-XDP-LOAD-UNLOAD.ps1
  Testscripts/Windows/VERIFY-XDP-MTU.ps1
  Testscripts/Windows/VERIFY-XDP-MULTIPLE-NICS.ps1
  XML/TestCases/FunctionalTests-DPDK.xml
Labels: enhancement

#996 Fix issue of Waiting VM start up with relative timeout according to VM size
  Libraries/CommonFunctions.psm1
  Testscripts/Windows/DiskHotAddRemove-Parallel.ps1
  Testscripts/Windows/DiskHotAddRemove-Serial.ps1
  Testscripts/Windows/NET-Add-NIC-After-Provision.ps1
  XML/TestCases/FunctionalTests-SRIOV.xml
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified, enhancement
