Repository microsoft/lisa, pull requests merged in 2020-07, with the labels that each got.

#887 Added no VM reboot option in CPU offline testing iterations
  Testscripts/Windows/CPU-Offline.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests.xml
  XML/TestCases/StressTests.xml
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified

#892 Enable test on ready platform with SSH key, fix for running ntttcp test on ready platform
  Libraries/CommonFunctions.psm1
  Libraries/TestHelpers.psm1
  TestControllers/ReadyController.psm1
  TestProviders/ReadyProvider.psm1
  Testscripts/Windows/PERF-NETWORK-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
Labels: :thumbsup: PR-Verified, enhancement

#895 Verify FS/GS registers enabled
  Testscripts/Linux/validate-intel-sgx-driver.sh
Labels: enhancement

#869 New test: Validate Dependency Agent
  Testscripts/Linux/validate-da.sh
  Testscripts/Windows/VALIDATE-DA.ps1
  XML/TestCases/FunctionalTests.xml
Labels: :smiley: Ready-For-Review

#894 New test development - CPU-OFFLINE-STORAGE-WORKLOAD
  Testscripts/Linux/CPUOfflineKernelBuild.sh
  Testscripts/Linux/channel_change.sh
  Testscripts/Windows/CPU-Offline.ps1
  XML/TestCases/FunctionalTests.xml
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified, Verified_Canonical, Verified_Redhat, Verified_SUSE

#899 Add retry in Upload-TestResultToDatabase, rename runtest.sh to include TestID to avoid conflict
  Libraries/Database.psm1
  Libraries/TestHelpers.psm1
Labels: :thumbsup: PR-Verified, Verified_Canonical

#901 Add validation for load module intel_sgx
  Testscripts/Windows/VALIDATE-INTEL-SGX-DRIVER.ps1
Labels: enhancement

#903 Add a ignorable failed log
  XML/Other/ignorable-boot-errors.xml
Labels: enhancement

#907 Extend to 55000 connections for ntttcp test and add more information
  Testscripts/Linux/perf_ntttcp.sh
  Testscripts/Windows/PERF-NETWORK-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/PerformanceTests.xml
Labels: enhancement

#912 Escape the character when replace the string in XML file.
  TestControllers/TestController.psm1
Labels: enhancement

#911 Update How-to-use.md
  Documents/How-to-use.md
Labels: :smiley: Ready-For-Review

#913 ntttcpTest.log was removed, fix nested cases
  Testscripts/Linux/nested_hyperv_ntttcp_different_l1_nat.sh
  Testscripts/Linux/nested_hyperv_ntttcp_different_l1_public_bridge.sh
  Testscripts/Linux/nested_kvm_ntttcp_different_l1_nat.sh
  Testscripts/Linux/nested_kvm_ntttcp_different_l1_public_bridge.sh
  Testscripts/Linux/nested_kvm_ntttcp_private_bridge.sh
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-NAT.ps1
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-NTTTCP-PRIVATE-BRIDGE.ps1
Labels: 🐞 Bug

#917 Upgrade before install packages.
  Testscripts/Linux/SetupRDMA.sh
Labels: 🐞 Bug

#902 Add new case about kernel debug for rhel
  Testscripts/Windows/KERNEL-DEBUG-BASIC.ps1
  XML/TestCases/FunctionalTests-KernelDebug.xml
Labels: enhancement

#928 Azure VM hibernation with Ubuntu 20.04, RHEL/CentOS 8.2
  Testscripts/Linux/SetupHbKernel.sh
  Testscripts/Windows/Power-Hibernate.ps1
  XML/Other/ReplaceableTestParameters.xml
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified, Verified_Canonical, Verified_Redhat

#925 Upload receiver's cycles/byte and fix the retransmit for multi-client
  Testscripts/Linux/perf_ntttcp.sh
  Testscripts/Windows/PERF-NETWORK-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
Labels: :smiley: Ready-For-Review

#930 Fix sshkey and osvhd issue.
  Libraries/Azure.psm1
  Libraries/CommonFunctions.psm1
  Libraries/TestHelpers.psm1
  TestControllers/AzureController.psm1
  TestControllers/TestController.psm1
  Utilities/Tool-Deploy-VM.ps1
  Utilities/UpdateGlobalConfigurationFromXmlSecrets.ps1
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified, enhancement, 🐞 Bug

#937 Get cpu count from vm directly. current design will fail the case when override the VM size.
  Testscripts/Linux/TIME-CLOCKEVENT.sh
  XML/TestCases/FunctionalTests.xml
Labels: :thumbsup: PR-Verified, 🐞 Bug

#936 Delete the definition of Run_SSHCommand in perf_ntttcp.sh
  Testscripts/Linux/perf_ntttcp.sh
  Testscripts/Linux/utils.sh
Labels: enhancement

#924 Fix setting sysemd config file for systemd v239 version
  Testscripts/Windows/PERF-NETWORK-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
  XML/Other/ReplaceableTestParameters.xml
Labels: :smiley: Ready-For-Review, enhancement

#932 PERF-XDP-RX-DROP: Single and multi-core test-cases
  Testscripts/Linux/pktgenSetup.sh
  Testscripts/Windows/PERF-XDP-RX-DROP.ps1
  XML/TestCases/PerformanceTests.xml
Labels: :smiley: Ready-For-Review, enhancement

#834 Add test case WALA-VERIFY-HOSTNAME-CHANGE
  Testscripts/Linux/WALA-VERIFY-FIREWALL-STATUS.py
  Testscripts/Linux/WALA-VERIFY-HOSTNAME-CHANGE.py
  XML/TestCases/FunctionalTests-WALA.xml
Labels: enhancement
