Repository microsoft/lisa, pull requests merged in 2020-02, with the labels that each got.

#697 Add retry to fix the issues in case RUNTIME_MEM_STRESSHOTREMOVE
  Testscripts/Windows/RUNTIME_MEM_STRESSHOTREMOVE.ps1
Labels: enhancement

#698 Fix DYNAMIC-MEMORY-STRESS-LARGE-CHUNK.
  Testscripts/Windows/DM-HOTADD-STRESS-NG.ps1
Labels: enhancement

#702 Add pending test count in test summary.
  Libraries/TestReport.psm1
  TestControllers/TestController.psm1
Labels: PR-Verified

#703 Fix VPP test case against Ubuntu.
  Testscripts/Linux/build_test_vpp.sh
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-DPDK.xml
Labels: enhancement

#706 Fix issue when convert datetime.
  Libraries/Azure.psm1
Labels: 🐞 Bug

#705 Fix replace parameter in TestParameters.xml
  LISAv2-Framework.psm1
Labels: 🐞 Bug

#708 Added a new Hibernation test
  Testscripts/Linux/SetupHbKernel.sh
  Testscripts/Windows/Power-Hibernate.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-Power.xml
  XML/VMConfigurations/OneVM.xml
Labels: Approved, PR-Verified

#699 Add Linux kernel self tests script
  Testscripts/Linux/Linux-Kernel-Self-Tests.sh
  Testscripts/Windows/Run-LksSuite.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/CommunityTests.xml
Labels: PR-Verified

#710 Fix test issues found in latest gallery image pipeline
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Windows/GPU-DRIVER-INSTALL.ps1
  Testscripts/Windows/VERIFY-ENABLE-DISABLE-SRIOV-ON-EXISTING-VM.ps1
Labels: 🐞 Bug

#712 improve library and hyperV common module to avoid run into bugs
  Libraries/HyperV.psm1
  Run-LisaV2.ps1
  Testscripts/Linux/DetectLinuxDistro.sh
  Testscripts/Linux/utils.sh
  Utilities/Get-LISAv2Statistics.ps1
Labels: PR-Verified

#717 Enable CONFIG_RTE_LIBRTE_MLX5_PMD when build DPDK.
  Testscripts/Linux/dpdkUtils.sh
Labels: 🐞 Bug

#718 DPDK - Fix insert data into database error when test_mode is not set.
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
Labels: 🐞 Bug
