Repository microsoft/lisa, pull requests merged in 2020-05, with the labels that each got.

#768 fix bug of deleting/collecting VMData from same ResourceGroup
  Libraries/Azure.psm1
  Libraries/TestHelpers.psm1
  TestControllers/TestController.psm1
  TestProviders/AzureProvider.psm1
  Testscripts/Windows/NET-Add-NIC-After-Provision.ps1
  Utilities/VmOfToday.ps1
Labels: 🐞 Bug

#769 variable name correction, 'groupName' to replace 'RGName'
  Libraries/Azure.psm1
Labels: 🐞 Bug

#771 fix bug of deleting/collecting VMData from same ResourceGroup,
  Libraries/Azure.psm1
  Libraries/CommonFunctions.psm1
  Run-LisaV2.ps1
  TestControllers/TestController.psm1
Labels: 🐞 Bug

#761 Stress test: Add FIO stress test with long time
  Testscripts/Linux/perf_fio.sh
  Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/StressTests.xml
Labels: enhancement

#785 add ignorable failure for hv_vss and hv_fcopy
  Testscripts/Linux/CreateRaid.sh
  XML/Other/ignorable-boot-errors.xml
Labels: Approved, enhancement

#787 Remove duplicate Priority setting for Power-hibernate and fix some typo
  Libraries/CommonFunctions.psm1
  Testscripts/Windows/LIS-INSTALL-SCENARIOS.ps1
  Testscripts/Windows/NET-Test-Vxlan.ps1
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  XML/TestCases/FunctionalTests-Power.xml
Labels: enhancement

#786 Add ignorable logs
  XML/Other/ignorable-boot-errors.xml
Labels: enhancement

#793 Fix libmnl-devel not found in 7.8
  Testscripts/Linux/dpdkUtils.sh
Labels: enhancement

#794 RHEL 7.8 missed dependencies and rdma_cm module
  Testscripts/Linux/SetupRDMA.sh
Labels: Approved, ⚠️ PR-UNDER-TEST, 🐞 Bug

#766 VERIFY-XDP-COMPLIANCE: New testcase to verify xdp
  Testscripts/Linux/XDPDumpSetup.sh
  Testscripts/Windows/VERIFY-XDP-COMPLIANCE.ps1
  XML/TestCases/FunctionalTests-XDP.xml
Labels: enhancement

#796 Fix fio setup dependency for RHEL 7.8
  Testscripts/Linux/utils.sh
Labels: PR-Verified, 🐞 Bug

#799 VERIFY-SRIOV-FAILSAFE-XDP: New Testcase to verify XDP on SRIOV/Synthetic NIC
  Testscripts/Windows/VERIFY-SRIOV-FAILSAFE-XDP.ps1
  XML/TestCases/FunctionalTests-XDP.xml
Labels: enhancement, ⚠️ PR-UNDER-TEST

#802 Fixed the format error
  Testscripts/Linux/LIS-Check-HypervDaemons-Files-Status.sh
  Testscripts/Linux/PC_Stop_VSS_Daemon.sh
  Testscripts/Linux/PartitionDisks.sh
  Testscripts/Linux/PartitionMultipleDisks.sh
  Testscripts/Linux/STOR_VHDXResize_GrowFSAfterResize.sh
  Testscripts/Linux/STOR_VSS_Check_VSS_Daemon.sh
  Testscripts/Linux/STOR_VSS_Disk_Fail.sh
  Testscripts/Linux/STOR_VSS_Disk_Mount_Multi_Paths.sh
  Testscripts/Linux/STOR_VSS_Disk_Mount_Squashfs.sh
  Testscripts/Linux/STOR_VSS_Disk_Stress.sh
  Testscripts/Linux/STOR_VSS_ISCSI_PartitionDisks.sh
  Testscripts/Linux/STOR_VSS_Set_VSS_Daemon.sh
  Testscripts/Linux/STOR_VSS_StopNetwork.sh
  Testscripts/Linux/SetupHbKernel.sh
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
Labels: 🐞 Bug

#805 Fix test issue on HyperV.
  Libraries/IntegrationServiceLibrary.psm1
  TestProviders/HyperVProvider.psm1
  Testscripts/Linux/ETHTOOL-GRO-LRO.sh
  Testscripts/Linux/SRIOV-VerifyVF-Connection.sh
  Testscripts/Linux/nvme_fstrim.sh
  Testscripts/Windows/FCOPY-NON-ASCII.ps1
Labels: enhancement

#800 CPU offline feature with vmbus interrupt re-assignement
  Testscripts/Linux/CPUOfflineKernelBuild.sh
  Testscripts/Linux/channel_change.sh
  Testscripts/Windows/CPU-Offline.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests.xml
Labels: Approved, Feature-Request, PR-Verified

#812 Fix issue for focal.
  Testscripts/Linux/containers_utils.sh
  Testscripts/Linux/gpu-driver-install.sh
Labels: enhancement

#814 Fix issues in KDUMP cases
  Testscripts/Windows/KDUMP-TestScript.ps1
  XML/TestCases/FunctionalTests.xml
Labels: Approved, 🐞 Bug

#806 Disable firewall in RHEL 7.8
  Testscripts/Linux/perf_fio_nfs.sh
Labels: Approved, PR-Verified

#815 CPU offline/online stress test case
  Testscripts/Windows/CPU-Offline.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/StressTests.xml
Labels: Approved, PR-Verified, enhancement

#818 Fix hit issue when there is no any warn/fail/error in dmesg
  Testscripts/Linux/VERIFY-BOOT-ERROR-WARNINGS.py
Labels: 🐞 Bug

#808 VERIFY-XDP-LOAD-UNLOAD: Testcase to verify successful loading unloading
  Testscripts/Windows/VERIFY-XDP-LOAD-UNLOAD.ps1
  XML/TestCases/FunctionalTests-XDP.xml
Labels: enhancement

#807 VERIFY-XDP-MULTIPLE-NICS: Testcase to verify XDP on multiple NICs
  Testscripts/Windows/VERIFY-XDP-MULTIPLE-NICS.ps1
  XML/TestCases/FunctionalTests-XDP.xml
Labels: enhancement

#816 OSU MPI Microbenchmarks for MVAPICH MPI testcase
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/BenchmarkTests-MPI.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
Labels: enhancement

#822 Added 2 negative tests to CPU offline/online test case
  Testscripts/Linux/channel_change.sh
Labels: Approved, PR-Verified

#823 Added 2 more verification points in CPU offline and vmbus channel interrupt re-assignement
  Testscripts/Linux/channel_change.sh
Labels: PR-Verified, enhancement

#827 Fix logic of WALA Firewall test case.
  Testscripts/Linux/WALA-VERIFY-FIREWALL-STATUS.py
Labels: enhancement

#825 Fix RDMA on SLES15SP1.
  Testscripts/Linux/SetupRDMA.sh
Labels: PR-Verified, enhancement

#835 Update kernel repo and branch name with public ones
  XML/Other/ReplaceableTestParameters.xml
Labels: :smiley: Ready-For-Review, :thumbsup: PR-Verified

#829 Verify scsi counter according to VM size and fix issues in LSVMBUS
  Testscripts/Linux/LSVMBUS.sh
  Testscripts/Windows/LSVMBUS.ps1
  XML/TestCases/FunctionalTests.xml
Labels: :smiley: Ready-For-Review, 🐞 Bug

#836 Fix platform.dist() removed in Python 3.8, obsolete since Python 2.7
  Testscripts/Linux/WALA-VERIFY-VERBOSE-ENABLED-LOGS.py
Labels: :smiley: Ready-For-Review, 🐞 Bug
