Repository microsoft/lisa, pull requests merged in 2020-01, with the labels that each got.

#677 Enable ssh keys authentication on Azure platform.
  LISAv2-Framework.psm1
  Libraries/Azure.psm1
  Libraries/CommonFunctions.psm1
  Libraries/TestHelpers.psm1
  README.md
  Run-LisaV2.ps1
  TestControllers/AzureController.psm1
  TestControllers/TestController.psm1
  Utilities/Tool-Deploy-VM.ps1
  XML/TestParameters.xml
Labels: enhancement

#680 Improvement for get subscription usage.
  Utilities/Get-SubscriptionUsage.ps1
  Utilities/Get-SubscriptionUsageTopVMs.ps1
Labels: enhancement, 🐞 Bug

#685 IMPI 2019 U6 refresh, Update dependencies, ofed driver in blob
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
Labels: Approved, rdma

#686 Fix DYNAMIC-MEMORY-VERIFY-UDEV
  Libraries/HyperV.psm1
  Testscripts/Linux/DM_HotAdd_Verify_udev.sh
  Testscripts/Windows/DM-CONFIGURE-MEMORY.ps1
Labels: enhancement

#688 Fix avoid interactive when install package.
  Testscripts/Linux/utils.sh
Labels: 🐞 Bug

#687 Fixed OMPI for SUSE images
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
  XML/Other/ReplaceableTestParameters.xml
Labels: PR-Verified, rdma

#690 Update for MVAPICH MPI refresh
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
Labels: PR-Verified, rdma

#691 RDMA/IB test duration shortened
  Testscripts/Linux/TestRDMA_MultiVM.sh
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
Labels: PR-Verified, rdma

#694 Update Hyper-V test cases.
  Testscripts/Linux/STOR_VHDXResize_PartitionDisk.sh
  Testscripts/Windows/AddVhdxHardDisk.ps1
  Testscripts/Windows/CLEANUP-Backup-DISK.ps1
  Testscripts/Windows/CORE-VerifyHeartBeat.ps1
  Testscripts/Windows/CORE-VerifyShutdown.ps1
  Testscripts/Windows/CORE-VerifyTimeSync.ps1
  Testscripts/Windows/LIS-Mount-CD.ps1
  Testscripts/Windows/LIS-Mount-FloppyDisk.ps1
  Testscripts/Windows/NUMA-Test.ps1
  Testscripts/Windows/RUNTIME-MEM-CONFIGURE.ps1
  Testscripts/Windows/RUNTIME-MEM-HOTADD.ps1
  Testscripts/Windows/RUNTIME_MEM_HOTADD_CHUNKS.ps1
  Testscripts/Windows/RUNTIME_MEM_HOTADD_REBOOT.ps1
  Testscripts/Windows/RUNTIME_MEM_MULTIPLEADDREMOVE.ps1
  Testscripts/Windows/Reboot-Diff-Memory-Settings.ps1
  Testscripts/Windows/SET-SECUREBOOT.ps1
  Testscripts/Windows/SETUP-Backup-DISK.ps1
  Testscripts/Windows/SETUP-RemoveIsoFromDvd.ps1
  Testscripts/Windows/SETUP-STOR-TakeRevert-Snapshot.ps1
  Testscripts/Windows/STOR-ExportImportVM.ps1
  Testscripts/Windows/STOR-VHDX-RESIZE-GROWFS.ps1
  Testscripts/Windows/STOR-VHDX-RESIZE-GROWSHRINK.ps1
  Testscripts/Windows/STOR-VSS-BACKUP-RESTORE-DISKSTRESS.ps1
  Testscripts/Windows/STOR-VSS-BACKUP-RESTORE-PARTITION.ps1
  Testscripts/Windows/STOR-VSS-Backup-Change-Hypervvssd.ps1
  Testscripts/Windows/STOR-VSS-Backup-Disable-Enable-VSS.ps1
  Testscripts/Windows/STOR-VSS-BackupRestore-Fail.ps1
  Testscripts/Windows/STOR-VSS-BackupRestore-ISO-NoNetwork.ps1
  Testscripts/Windows/STOR-VSS-BackupRestore-Mount-Multi-Paths.ps1
  Testscripts/Windows/STOR-VSS-BackupRestore-Mount-Squashfs.ps1
  Testscripts/Windows/STOR-VSS-BackupRestore-State.ps1
  Testscripts/Windows/STORAGE-DiffDiskGrowth.ps1
  Testscripts/Windows/STORAGE-HotUnplug.ps1
  Testscripts/Windows/Set-VM-Memory.ps1
Labels: enhancement
