Repository microsoft/lisa, pull requests merged in 2021-11, with the labels that each got.

#1620 name change for test to fit convention
  microsoft/testsuites/dpdk/dpdksuite.py
Labels: trivial

#1621 Remove some annoying nic info messages
  lisa/nic.py
Labels: trivial

#1595 Refine sriov test cases, migrate reload module test.
  lisa/nic.py
  lisa/tools/__init__.py
  lisa/tools/ethtool.py
  lisa/tools/firewall.py
  lisa/tools/iperf3.py
  lisa/tools/kill.py
  lisa/tools/lspci.py
  lisa/tools/modprobe.py
  lisa/tools/pgrep.py
  lisa/tools/service.py
  lisa/tools/ssh.py
  lisa/util/process.py
  microsoft/testsuites/network/sriov.py
Labels: 🆕 LISAv3

#1627 Fix TVM issue on debian.
  Testscripts/Linux/TVM-TestMeasuredBootCompatibility.sh
  Testscripts/Linux/TVM-TestSecureBootCompatibility.sh
Labels: 🐞 Bug

#1626 Make availability_set as optional when deploy vm using template on Azure.
  lisa/sut_orchestrator/azure/arm_template.json
  lisa/sut_orchestrator/azure/platform_.py
Labels: 🆕 LISAv3

#1629 Fix permission issue when get grub file.
  lisa/operating_system.py
  lisa/transformers/kernel_installer.py
Labels: 🆕 LISAv3

#1640 Fix issue when build upstream kernel
  lisa/operating_system.py
  lisa/tools/xfstests.py
  lisa/transformers/kernel_source_installer.py
Labels: 🆕 LISAv3
