Repository microsoft/lisa, pull requests merged in 2021-03, with the labels that each got.

#1197 Add absolute path for SB and MB info tools
  Testscripts/Linux/TVM-TestMeasuredBootCompatibility.sh
  Testscripts/Linux/TVM-TestSecureBootCompatibility.sh
Labels: 🐞 Bug

#1162 Add case lsvmbus.
  lisa/tools/__init__.py
  lisa/tools/lsvmbus.py
  lisa/tools/wget.py
  testsuites/basic/lsvmbus.py
Labels: 🆕 LISAv3

#1202 Increase time out for get-azresource, keep previous value when UseExistingRG.
  Libraries/Azure.psm1
  TestProviders/AzureProvider.psm1
Labels: enhancement

#1204 Add missing property for can_install method in lsvmbus.
  lisa/tools/lsvmbus.py
Labels: 🆕 LISAv3

#1200 Remove empty or none results from matched results; update pattern to match OsVHD.
  lisa/runners/legacy_runner.py
Labels: 🆕 LISAv3

#1207 SGX - update clang-7 to clang-8
  Testscripts/Linux/validate-intel-sgx-driver.sh
Labels: 🐞 Bug

#1203 Update area of some cases
  Documents/LISAv2-TestCase-Statistics.md
  XML/TestCases/FunctionalTests-KernelDebug.xml
  XML/TestCases/FunctionalTests-SGX.xml
  XML/TestCases/FunctionalTests.xml
  XML/TestCases/PerformanceTests.xml
Labels: enhancement

#1208 support enable in runners.
  lisa/runner.py
  lisa/schema.py
  lisa/tests/test_testselector.py
  lisa/testselector.py
Labels: 🆕 LISAv3

#1209 Add concepts document
  docs/concepts.md
  docs/img/req_cap.png
  docs/write_case.md
Labels: 🆕 LISAv3

#1210 Fix bug, sort() function return none, assert is invaild.
  testsuites/basic/lsvmbus.py
Labels: 🐞 Bug

#1211 Legacy - filter out StorageAccountType in SetupConfig
  lisa/runners/legacy_runner.py
Labels: 🆕 LISAv3

#1214 Fix issues.
  Libraries/CommonFunctions.psm1
  Testscripts/Linux/KDUMP-Config.sh
  Testscripts/Windows/DiskHotAddRemove-Parallel.ps1
Labels: enhancement, 🐞 Bug

#1217 Get information from legacy run.
  lisa/testsuite.py
Labels: 🆕 LISAv3, 🐞 Bug

#1219 Fix for legacy run.
  lisa/runners/legacy_runner.py
Labels: 🆕 LISAv3

#1218 Update pattern for extract value from SetupConfig.
  lisa/runners/legacy_runner.py
Labels: 🆕 LISAv3

#1220 CPU count is needed value.
  lisa/tools/lscpu.py
Labels: 🆕 LISAv3

#1222 fix failed on access non-exists node
  lisa/sut_orchestrator/azure/platform_.py
Labels: 🆕 LISAv3

#1221 Work around for nic_count is 0 return from size sku capabilities.
  lisa/sut_orchestrator/azure/platform_.py
Labels: 🆕 LISAv3

#1225 Fix failure in importing
  lisa/util/module.py
Labels: 🆕 LISAv3

#1223 Switch to download lsvmbus when encounter issue during install package.
  lisa/executable.py
  lisa/operating_system.py
  lisa/tools/lsvmbus.py
  lisa/tools/wget.py
Labels: 🆕 LISAv3

#1216 Change image as lower case.
  lisa/sut_orchestrator/azure/platform_.py
Labels: 🆕 LISAv3

#1233 Node: fix is_connected is incorrect after reboot
  lisa/node.py
  lisa/sut_orchestrator/azure/platform_.py
  lisa/util/shell.py
Labels: 🆕 LISAv3

#1226 attach a test result to prepare failure.
  lisa/runners/lisa_runner.py
  lisa/runners/tests/test_lisa_runner.py
Labels: 🆕 LISAv3

#1232 Fix multiple process access the same log file issue.
  lisa/runners/legacy_runner.py
  poetry.lock
  pyproject.toml
Labels: 🆕 LISAv3

#1228 Change the rule for selecting test cases to be the union of TestNames with the join of other group filter conditions
  Libraries/CommonFunctions.psm1
Labels: enhancement

#1235 Throw out exception when encounter issue during clone code or checkout branch.
  lisa/tools/git.py
Labels: 🆕 LISAv3

#1236 Fix remote is initialized to local incorrectly.
  lisa/node.py
Labels: 🆕 LISAv3

#1238 Extend install packages time.
  lisa/operating_system.py
Labels: 🆕 LISAv3

#1237 Update pattern of matching log to meet new log format, comatible with old format.
  lisa/runners/legacy_runner.py
Labels: 🆕 LISAv3

#1242 Update runbook files for lisa and legacy run.
  microsoft/runbook/azure.yml
  microsoft/runbook/tiers/t1.yml
  microsoft/runbook/tiers/t2.yml
  microsoft/runbook/tiers/t3.yml
  microsoft/runbook/tiers/t4.yml
  microsoft/runbook/tiers/tier.yml
Labels: 🆕 LISAv3

#1241 update development document
  Makefile
  docs/development.md
  docs/extension.md
  docs/write_case.md
Labels: 🆕 LISAv3

#1245 Add workaround for expired RHUI client certificate issue on old RHEL VM image.
  lisa/operating_system.py
Labels: 🆕 LISAv3

#1247 capture failure on gets env info hooks
  lisa/environment.py
  lisa/platform_.py
Labels: 🆕 LISAv3

#1249 Implement the extension document
  docs/extension.md
  lisa/notifier.py
  lisa/sut_orchestrator/azure/platform_.py
Labels: 🆕 LISAv3

#1254 Fix mypy paths in vscode
  .env
  docs/development.md
Labels: 🆕 LISAv3

#1253 Update pattern to match the host version from dmesg.
  lisa/sut_orchestrator/azure/platform_.py
Labels: 🆕 LISAv3

#1257 fix cannot get deployment info
  lisa/sut_orchestrator/azure/platform_.py
Labels: 🆕 LISAv3
