Repository microsoft/lisa, pull requests merged in 2021-04, with the labels that each got.

#1266 Add offer_type when accept term for a plan.
  lisa/sut_orchestrator/azure/platform_.py
Labels: 🆕 LISAv3

#1269 Extend timeout for 'yum update', there are still some time out cases for small size.
  lisa/operating_system.py
Labels: 🆕 LISAv3

#1276 Update get_storage_account_name function signature
  lisa/sut_orchestrator/azure/common.py
  lisa/sut_orchestrator/azure/platform_.py
Labels: 🆕 LISAv3

#1277 Add storage account container creation function
  lisa/sut_orchestrator/azure/common.py
  poetry.lock
  pyproject.toml
Labels: ❓ Question

#1272 Fix test cases issues.
  Testscripts/Linux/nested_kvm_ntttcp_private_bridge.sh
  Testscripts/Linux/nested_vm_utils.sh
  Testscripts/Windows/PERF-NETWORK-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
  Testscripts/Windows/RELOAD-MODULES.ps1
Labels: enhancement

#1288 Add variable 'marketplace_image' definition in azure.yaml.
  microsoft/runbook/azure.yml
Labels: 🆕 LISAv3

#1286 Fix some issues on hibernation cases
  Testscripts/Linux/ETHTOOL-OFFLOADING-SETTING.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/HB-CLOCKSYNC.ps1
  Testscripts/Windows/Power-Hibernate.ps1
  Testscripts/Windows/WORKLOAD-HB.ps1
Labels: enhancement

#1283 Use `admin_private_key_file` variable in ready.yml
  microsoft/runbook/ready.yml
Labels: 🆕 LISAv3

#1293 Fix hung issue on channel.recv_exit_status()
  lisa/util/shell.py
Labels: 🆕 LISAv3

#1297 Add two cases.
  XML/TestCases/FunctionalTests.xml
Labels: enhancement
