Repository microsoft/lisa, pull requests merged in 2021-02, with the labels that each got.

#1164 DPDK/netvsc: Adding Netvsc device setup reset
  Testscripts/Linux/dpdk-testFWD.sh
  Testscripts/Linux/dpdk-testPMD.sh
  Testscripts/Linux/dpdkTestPmd.sh
  Testscripts/Linux/dpdkUtils.sh
Labels: :smiley: Ready-For-Review, dpdk, enhancement

#1165 install: dpdk: install elftools
  Testscripts/Linux/dpdkUtils.sh
Labels: :smiley: Ready-For-Review, dpdk

#1163 dpdk-ovs setup: changes to adopt dpdk-meson build
  Testscripts/Linux/ovs_setup.sh
Labels: dpdk, enhancement

#1179 Update GetAndCompareOsLogs to return the delta logs, and attach the delta logs to TestSummary
  Libraries/TestLogs.psm1
  TestControllers/TestController.psm1
Labels: enhancement

#1186 Fix for collecting legacy cases.
  lisa/runners/legacy_runner.py
Labels: 🆕 LISAv3

#1185 Add NotRun, Skipped exceptions for test case
  lisa/tests/test_testsuite.py
  lisa/testsuite.py
  lisa/util/__init__.py
Labels: 🆕 LISAv3

#1190 Update pattern to get more info from legacy logs.
  lisa/runners/legacy_runner.py
Labels: 🆕 LISAv3

#1191 Fix collect test cases in legacy run.
  lisa/runners/legacy_runner.py
Labels: 🆕 LISAv3

#1192 Update matched test status from legacy run.
  lisa/runners/legacy_runner.py
Labels: 🆕 LISAv3

#1193 Fix for comparing runtime info.
  lisa/runners/legacy_runner.py
Labels: 🆕 LISAv3

#1177 meson-0.57.0 needs python 3.6.
  Testscripts/Linux/dpdkUtils.sh
Labels: dpdk
