Repository microsoft/lisa, pull requests merged in 2021-01, with the labels that each got.

#1143 Update description to clarify - code doesn't support install the tool not distro itself.
  lisa/executable.py
Labels: 🆕 LISAv3

#1145 Add publisher name opensuse-leap.
  lisa/operating_system.py
Labels: 🆕 LISAv3

#1144 Smoke test enhancement.
  lisa/sut_orchestrator/azure/tools.py
  lisa/tools/reboot.py
Labels: 🆕 LISAv3

#1146 Fix issues on HyperV platform
  Libraries/HyperV.psm1
  Libraries/WorkingSpaceManagement.psm1
  README.md
  XML/GlobalConfigurations.xml
Labels: 🐞 Bug

#1148 Retrieve VM info again after VM start.
  TestControllers/TestController.psm1
  TestProviders/HyperVProvider.psm1
Labels: 🐞 Bug

#1150 Azure: Ignore provisioning internal exception.
  lisa/sut_orchestrator/azure/platform_.py
Labels: 🆕 LISAv3

#1152 Update error description clearly when run uptime -s.
  lisa/tools/uptime.py
Labels: 🆕 LISAv3

#1153 Extend timeout during set up ssh connection.
  lisa/util/shell.py
Labels: 🆕 LISAv3

#1154 Add DefaultResultTable to P1 perf cases, pass TestPassID to the perf tables, adjust priority for several cases
  Libraries/Database.psm1
  TestControllers/TestController.psm1
  XML/TestCases/PerformanceTests.xml
Labels: enhancement

#1158 Add -y to avoid manual interaction.
  Testscripts/Linux/docker_dotnet_app.sh
Labels: 🐞 Bug

#1156 Fix DPDK issues.
  Testscripts/Linux/build_install_rdma_core.sh
  Testscripts/Linux/dpdkUtils.sh
Labels: 🐞 Bug

#1159 DPDK - Load needed modules before testing.
  Testscripts/Linux/dpdkPmdsBasicCheck.sh
Labels: dpdk
