Repository microsoft/lisa, pull requests merged in 2021-12, with the labels that each got.

#1638 Migrate boot_with_debug_kernel test case.
  lisa/__init__.py
  lisa/tools/reboot.py
  lisa/util/__init__.py
  lisa/util/shell.py
  microsoft/testsuites/core/boot.py
  microsoft/testsuites/core/provisioning.py
  microsoft/testsuites/network/sriov.py
Labels: 🆕 LISAv3

#1645 Add one more clock source for new host version.
  microsoft/testsuites/core/timesync.py
Labels: 🆕 LISAv3

#1654 debian backport versions can contain tilde in build info
  lisa/operating_system.py
Labels: trivial

#1655 💡 [shell] Document some shell entries
  lisa/util/shell.py
Labels: 🆕 LISAv3, doc_improvement

#1660 Fix build issue related certificate in image ubuntu 21.04
  lisa/transformers/kernel_source_installer.py
Labels: 🆕 LISAv3

#1663 -y is indeed needed
  lisa/operating_system.py
Labels: trivial

#1667 Skip replace boot kernel for focal gen2 + fde kernel.
  lisa/transformers/kernel_installer.py
Labels: 🆕 LISAv3

#1670 Fix create SP script based on latest Azure PS change.
  Utilities/CreateServicePrincipal.ps1
Labels: 🐞 Bug
