Repository microsoft/lisa, pull requests merged in 2021-06, with the labels that each got.

#1347 Fix for hot resize.
  Testscripts/Windows/VM-HOT-RESIZE.ps1
Labels: enhancement

#1348 Update detect_linux_distribution function
  Testscripts/Linux/utils.sh
Labels: enhancement

#1352 Use exact match when check whether the package installed or not.
  lisa/operating_system.py
Labels: 🆕 LISAv3

#1345 Migrate time sync test cases.
  lisa/operating_system.py
  lisa/tools/lscpu.py
  lisa/util/process.py
  microsoft/testsuites/core/timesync.py
Labels: 🆕 LISAv3

#1364 Part1 - Add NVMe test suite.
  lisa/features/__init__.py
  lisa/features/nvme.py
  lisa/sut_orchestrator/azure/features.py
  lisa/sut_orchestrator/azure/platform_.py
  lisa/tools/__init__.py
  lisa/tools/nvmecli.py
  microsoft/testsuites/nvme/nvme.py
Labels: 🆕 LISAv3

#1377 Update for timesync_check_unbind_clocksource to count tsc/constant_tsc shown up times.
  lisa/sut_orchestrator/azure/platform_.py
  microsoft/testsuites/core/timesync.py
Labels: 🆕 LISAv3

#1385 Fix test case issues.
  Testscripts/Linux/dpdk_verify_primary_secondary.sh
  Testscripts/Linux/nvme_blkdiscard.sh
  Testscripts/Windows/VALIDATE-INTEL-SGX-DRIVER.ps1
Labels: 🐞 Bug
