Repository microsoft/lisa, pull requests merged in 2022-02, with the labels that each got.

#1747 Chown Tool: remove broken shell.chown and replace with node.tools[Chown]
  lisa/tools/__init__.py
  lisa/tools/chown.py
  lisa/util/shell.py
Labels: :smiley: Ready-For-Review

#1749 Add RedHat support to DpdkOvs test class
  lisa/node.py
  microsoft/testsuites/dpdk/dpdkovs.py
Labels: Verified_Redhat

#1751 Migrate VERIFY-LINUX-CONFIGURATION.
  microsoft/testsuites/core/azure_image_standard.py
Labels: 🆕 LISAv3

#1757 Fix issue for new changes in DCAP client.
  Testscripts/Linux/validate-intel-sgx-driver.sh
Labels: 🐞 Bug, :thumbsup: PR-Verified

#1759 Migrate VERIFY-BOOT-ERROR-WARNINGS
  microsoft/testsuites/core/azure_image_standard.py
Labels: 🆕 LISAv3
